### PR TITLE
API: Add additional output to QSO-call

### PR DESCRIPTION
**Pull request by tudacs**
Two return fields added for improved reporting:

    Messages returned from Logbook-import
    Number of QSO's added without message

To discuss:

    Number of QSO's depends on import-function returning empty string for successful import - maybe add documentation there
    Maybe add strings of errornous ADIF's to output?

I appreciate ideas/comments...

p.s. Sorry for this duplicate PR - I saw no way to change the PR to dev-branch :(

### CODE REVIEW

**Comment by magicbug** [comment]
As its a seperate record in the json should be ok, do we think the field names OK for the data its representing?

**Comment by int2001** [comment]
Good point, Peter.
i think messages is OK.
But instead of "created" i suggest: "created_cnt". Its more representative for the value

**Comment by magicbug** [comment]
Yeah or imported_count perhaps i'm happy with either then it can be merged

**Comment by int2001** [comment]
Yes, same view as Peter. @tudacs can you rename the param pse?

**Comment by tudacs** [comment]
Sure, thank you for your comments and suggestions!

**Comment by magicbug** [comment]
I'm good with it now!

**Pull request merged**
