### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by cats-shadow**
Russian translation update

### CODE REVIEW

**Comment by HB9HIL** [comment]
Hello @cats-shadow 
Thank you for your effort to help translating Cloudlog. unfortunately we have a conflict here. Could you please resolve them?
Seems like the conflicts appear in `filter_lang.php`

**Review by HB9HIL — CHANGES_REQUESTED** [review]
resolve conflicts

**Comment by cats-shadow** [comment]
> Seems like the conflicts appear in `filter_lang.php`

Done.

**Review by HB9HIL — APPROVED** [review]
tested. works ok

**Pull request merged**
