### PR TITLE
Fixes #2295 // Fill station_callsign when provided empty by adif

### LINKED ISSUE #2295: ADIF - If importing and station_callsign isn't provided check if OPERATOR is
If importing an ADIF file and station_callsign isn't provided check if OPERATOR is and use that instead thus suppressing unnecessary erroring.

photo_2023-07-15_10-58-52

Get rid of those errors! :)

Possibly might want to change the error to say that said tag was missing or incorrect rather than just wrong

Thanks G0ABI for reporting

### PR DESCRIPTION
**Pull request by int2001**
Populate station_callsign with chosen profile-call when ADIF has empty station_callsign.

### CODE REVIEW

**Comment by AndreasK79** [comment]
Tested importing without station callsign ok.
Tested importing with correct station callsign ok.
Tested importing with different station callsign gave an error.

Go for merge.

**Comment by AndreasK79** [comment]
@magicbug this was also merged to master.

**Comment by magicbug** [comment]
oops!

**Comment by magicbug** [comment]
pushed to dev too, seems to be working ok however

**Comment by magicbug** [comment]
I shouldn't touch Github when i feel pants :D

**Comment by AndreasK79** [comment]
It can happen to anyone.

**Pull request merged**
