### PR TITLE
[Bands] Now saves when clicking checkbox

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by AndreasK79** [comment]
@magicbug this is what we discussed. It will create several call for saving to the database, but I guess you aren't editing the bands that often. I guess it's more of a set and forget.

**Comment by phl0** [comment]
Tested ok on my end. Bands configuration now in the user's menu.

**Comment by AndreasK79** [comment]
@phl0 thanks for testing. I also need to add WWFF to the configuration, thanks to you :)

**Comment by magicbug** [comment]
Lovely! much more user friendly i think

**Comment by AndreasK79** [comment]
Then it's merge time :)

**Pull request merged**
