### PR TITLE
[WIP] Dockerize Cloudlog

### PR DESCRIPTION
**Pull request by dgdavid**
Hi there!

First things first: thank you a lot guys for your work here as well as for making it open source :heart:

Now, the context of this (and two more comings) PR:

After a little research, @leroydiazg and I concluded that Cloudlog could be a perfect fit for our father (known in the amateur radio world as [EA8CPU](https://www.qrz.com/db/EA8CPU)) track his _QSOs_. But, before setting an instance for him, we'd have to translate it to Spanish. However, we soon realized that almost all _application strings_ were_ hardcoded.

That's why we met past [Jan 3rd](https://github.com/dgdavid/Cloudlog/commits/add-spanish-translations) to

* Dockerize the application, to speed up the development process.

  Probably a whim from my side, but, apart from all advantages of containerization, it would be great to just type `docker-compose up` and have the application running without caring about the requirements. Wouldn't it?

  This is what this PR intends for. Let's talk about it later on.
	
* Add support for internationalization.

   As said, we found a lot of hardcoded text in the application, although this is [partially not longer true after Jan 5th](https://github.com/magicbug/Cloudlog/commit/5623b004c1722509363721d94da3a1ece347b7c3). So we started going through the application and extracting them into language files.

  See #799.
	 
* Add the Spanish translations.
  
  See #800.

So, this is the PR intended for _dockerize_ Cloudlog. 

As my Docker knowledge is very basic and my first contact with CodeIgniter X was three weeks ago or so (when we found Cloudlog),  I started playing with the [detailed example](https://avenir.ro/codeigniter-4-using-docker-apache-mysql/) made by @avenirer.

But the idea would be to simplify it a bit, use a MariaDB image instead of the MySQL one, and try to _automate_, if possible, the Cloudlog installation. What do you think, @magicbug?

### CODE REVIEW

**Comment by dgdavid** [comment]
BTW, @magicbug 

I have been wondering if you consider going a step forward with Cloudlog and update it to use a more up-to-date stack. As far as I can see, 

* [a long time ago](https://github.com/magicbug/Cloudlog/issues/171#issuecomment-127771632), you were tempted/evaluating to re-write it using Laravel

* upgrading to the latest CodeIgniter version [isn't technically possible](https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_4xx.html)

Do you plan to start from scratch at any point?

I'm not sure if I could help. Even more, I cannot do strong commitments to such regard, but I'm asking it because I think it is a good idea to start a public discussion in case you're interested.

**Comment by magicbug** [comment]
Currently no plans to rewrite, it will probably happen but no time soon, Cloudlog with CI3 won't stop working any time soon.

That being said no idea what I'd end up using, quite a few of the frameworks have become too opinionated.

Fantastic on Docker, it's worth pointing out there's a few of them on GitHub not tried any of them, but Cloudlog does have static assets requirements especially if you want to store QSL card images & also eQSL digital card backups.

**Comment by dgdavid** [comment]
> Currently no plans to rewrite, it will probably happen but no time soon, Cloudlog with CI3 won't stop working any time soon.

Good to know, thanks.

> Fantastic on Docker, it's worth pointing out there's a few of them on GitHub not tried any of them, 

Thanks for the hint! It didn't occur to me to [search for "cloudlog docker" on Github](https://github.com/search?q=cloudlog+docker) :man_facepalming::man_facepalming::man_facepalming: A couple of them that looks really interesting, I'll give them a try as soon as possible since I intend to provide an automated installation too.

> but Cloudlog does have static assets requirements especially if you want to store QSL card images & also eQSL digital card backups.

Not sure what you mean or where is the problem. A [volume](https://docs.docker.com/storage/volumes/) could be used, right?

So, now the question is, are you open to include a docker/docker-compose in the Cloudlog repo?

**Comment by dgdavid** [comment]
> I'll give them a try as soon as possible

Definitely, the [fully automatization](https://github.com/tx44/cloudlog-docker) made by @tx44 is awesome. Much more that what I wanted to achieve. It would be nice either, to make it part of Cloudlog or to add a reference to it in the documentation.

> are you open to include a docker/docker-compose in the Cloudlog repo?

As said before, I think the work is already done and there is no reason to reinvent the wheel. From my side, I'll add some questions/proposal in https://github.com/tx44/cloudlog-docker and encourage you to give it a try by yourself and considered whatever of my previous proposals.

So, continue working on this PR makes no sense anymor. Closing it.

**Pull request closed without merging**
