### PR TITLE
eqsl: add date force update

### PR DESCRIPTION
**Pull request by abarrau**
Add a field to add a date if necessary, in order to resynchronize the eQsl to an earlier date.

### CODE REVIEW

**Review by int2001 — CHANGES_REQUESTED** [review]
Tested this. It works as propagated. Like that feature.

But: Can you please adjust the view? Seems a little "unformatted". I suggest an extra row for it. See Screenshot.

image

**Comment by abarrau** [comment]
Hello, 
Do you prefer it like this?

image

**Comment by abarrau** [comment]
ok, I added a alt text

**Comment by abarrau** [comment]
@int2001, i update import view file, you can check if it's ok for you now ;)

**Comment by magicbug** [comment]
Yep thats better

**Pull request merged**
