### PR TITLE
Configurable modes

### PR DESCRIPTION
**Pull request by dg9vh**
This PR makes mode-list editable and prefilled with all actually listed modes from ADIF-Spec. in Edit mode and prefilled with those as before.

Now Users can activate/deactivate modes from being shown within the Mode-selection in new-QSO-logging-windows.

### CODE REVIEW

**Comment by magicbug** [comment]
This looks interesting, I think one thing that needs to improve is comments so that it's obvious what the controllers/models tasks are this is something that needs to be improved across the board within the Cloudlog codebase going forward.

Will give it a test and some feedback this evening!

**Comment by dg9vh** [comment]
Nice to hear :-) 

Just go testing - we can do some good documentation on it... but I think, it would be usable for novices :-)

**Comment by AndreasK79** [comment]
Excellent. I was thinking about something like this, since the modes were locked down with the change to a dropdown that I did. 

Several modes are hardcoded in javascript with default reports. Should this somehow be implemented with a default report, so that the javascript fetches from this?

**Comment by dg9vh** [comment]
I actually had problems within the frequency-library to get the infos from the modes-model... no idea how to solve this... It could be an idea to put default-reports also into a column in the database...

**Comment by magicbug** [comment]
One other thing that would be an improvement to the system is modes and sub modes as that keeps coming up

**Comment by dg9vh** [comment]
If I get an idea on how to realize it, we can fill both fields in adif with correct values but only have the modes in one list to choose from...

For example: if you choose PSK31 it would resolve to mode = PSK and submode = PSK31.

On database, we can add a column parent mode containing the main-mode... if empty, we know, that mode = main-mode so no submode is to be filled... or we can have 2 columns "mode" and "submode"... but that means, rebuilding the table from scratch :-)
Would be not a big problem... would think about it... on how to do it... and on how to map it into corresponding fields.

**Comment by dg9vh** [comment]
I added support for sub-modes on different levels...

**Comment by dg9vh** [comment]
Some further additions of submode ... I think, I now catched all..

**Comment by dg9vh** [comment]
@magicbug what's about merging this PR into the master?

**Comment by dg9vh** [comment]
@magicbug Hi Peter, what's open on this pull-request that hides you from merging?

**Comment by ofadam** [comment]
I tried this commit out and it seems to work well – I can not only see the submode when applicable on log screens, but can also see the submodes listed as nested items when editing a QSO. I couldn't find any issues. Nicely done!

**Comment by dg9vh** [comment]
hi @magicbug what's exactly the problem with merging this feature into the main-code? We are idling around about for 3 months now without any specific problem mentioned on this PR but with no moving...

Please merge it into the code, it locks serveral other developments here on a stale state.

**Comment by dg9vh** [comment]
mni tnx fer merging :-)

**Comment by magicbug** [comment]
If you can just drive it a brief overview in the wiki for people that would be useful.

**Comment by dg9vh** [comment]
Already started at https://github.com/magicbug/Cloudlog/wiki/QSO-Modes

**Pull request merged**
