### PR TITLE
Handle VUCC grid lines and corners in Qrb mapping

### PR DESCRIPTION
**Pull request by phl0**
The current code regarding mapping does not handle VUCC grid lines and corners. In such cases it just strips off the first 4-char grid and take the center of this for mapping.
This change calculates the coordinates from VUCC_GRIDS by determining the grid corner of the center of a grid line.

### CODE REVIEW

**Comment by phl0** [comment]
Example screenshots:

Screenshot from 2023-08-23 14-17-57

Screenshot from 2023-08-23 13-20-47

**Comment by phl0** [comment]
Go for merge.

**Comment by magicbug** [comment]
Ha, do you read my mind or something, was just checking to see if you'd pulled this out of draft haha

**Comment by phl0** [comment]
Good timing. Tnx :)

**Pull request merged**
