### PR TITLE
DXCC Warning

### PR DESCRIPTION
**Pull request by HB9HIL**
Added a warning in Station Location if a User is choosing a deleted DXCC.

### CODE REVIEW

**Comment by AndreasK79** [comment]
Tested working.

image

Good job! Go for merge.

**Comment by phl0** [comment]
Tested and looks good to me :) Go for merge

**Comment by magicbug** [comment]
Good idea, however would be better if it used the bootstrap alerts like we use around other places in Cloudlog see https://getbootstrap.com/docs/4.6/components/alerts/ this will keep formatting.

**Comment by phl0** [comment]
Works for me :)

**Comment by AndreasK79** [comment]
Me too.

**Pull request merged**
