### PR TITLE
Jump to RSTr after callsign input

### PR DESCRIPTION
**Pull request by phl0**
Align tab index as per https://github.com/magicbug/Cloudlog/discussions/3083.

### CODE REVIEW

**Comment by phl0** [comment]
@GregTroar Pls test and report.

**Comment by GregTroar** [comment]
which branch should I use ?

**Comment by phl0** [comment]
> which branch should I use ?

It is sitting in my branch under https://github.com/phl0/Cloudlog/tree/tabindex until @magicbug merges this one to dev.

**Comment by GregTroar** [comment]
ok will try when I can pull it

**Pull request closed without merging**
