### PR TITLE
Lotw information

### PR DESCRIPTION
**Pull request by AndreasK79**
This PR makes LoTW user information more visible in the advanced logbook:
image

A search has been added to find unconfirmed LoTW QSOs where QSO partner has uploaded after QSO date:
image

Information about LoTW user and last upload is displayed in the QSO popup:
image

Need to run http://cloudlog-url/index.php/update/lotw_users to populate table. This can also be run as a cron job.

### CODE REVIEW

**Comment by phl0** [comment]
Working fine here. Really like this feature. Though LoTW csv file seems to be updated rather infrequently. :(

**Comment by magicbug** [comment]
Looks good, agree with Flo the lotw csv is updated not enough by them!

**Comment by phl0** [comment]
> Looks good, agree with Flo the lotw csv is updated not enough by them!

I am watching the file since Thursday and no change. Should we add a disclaimer somewhere? But where?

**Comment by magicbug** [comment]
In the debug section we could say when the file was last updated?

**Pull request merged**
