### PR TITLE
Auto QTH function configurable on frontend

### PR DESCRIPTION
**Pull request by phl0**
This addresses https://github.com/magicbug/Cloudlog/discussions/1698 and make it user-configurable on frontend.

### CODE REVIEW

**Comment by m0urs** [comment]
In general both functions are working for me. However, automatic creation of the missing field "user_qth_lookup" did not work. Both "application/migrations/103_add_user_wwff_lookup.php" and "application/migrations/104_user_auto_qth_option.php" are creating the same field ("user_wwff_lookup"). Looks like a copy&paste error?

**Comment by m0urs** [comment]
And maybe it would be possible to also change the link, which appears after entering a WWFF reference, from WWFF to https://www.cqgma.org/ ?

**Comment by phl0** [comment]
Mistake fixed. The WWFF link stuff is handled in https://github.com/magicbug/Cloudlog/pull/1699.

**Comment by m0urs** [comment]
Ok, I only changed one link in #1699 yet, so I will change the other occurence as well in my PR

**Pull request merged**
