### PR TITLE
Statistics reworked

### PR DESCRIPTION
**Pull request by AndreasK79**
Changed from using Google Chart to Chart.js
Upgraded Chart.js to latest version.

### CODE REVIEW

**Comment by phl0** [comment]
I like the new view. But it seems some graphs are cut off in my case:

Screenshot from 2022-09-18 17-32-08

Screenshot from 2022-09-18 17-32-16

**Comment by AndreasK79** [comment]
Thanks for testing. My log didn't contain enough data to show that problem. I'll take a look.

**Comment by AndreasK79** [comment]
@phl0 refresh and give it another go. The outlabel plugin I use, is kinda tricky to get right.
Might split into several tabs, and not have chart and table side by side.

**Comment by phl0** [comment]
Well ... better :)

Screenshot from 2022-09-18 18-03-42

Screenshot from 2022-09-18 18-03-35

**Comment by AndreasK79** [comment]
You need to work more on bands and satellites with few QSOs :)

If the plugin could put the labels on the other side, instead of just stacking them on top, it would not need as much space. Guess I need to research the code more.

**Comment by phl0** [comment]
Na no worries. My log is a little SAT-centric. I agree :)

**Comment by AndreasK79** [comment]
@phl0 This is very tricky to fix, since those with few QSOs will be stacked above each other.

Just for the fun of it. Could you edit statistics.js and add rotation: -45, after line 315 and 441 right after "options: {"?

**Comment by phl0** [comment]
Good on the general one. But worse on the SAT page :)

Screenshot from 2022-09-18 20-50-45

Screenshot from 2022-09-18 20-50-36

**Comment by AndreasK79** [comment]
Thanks. I've been looking into the code for the label-plugin, but I'm not sure how to fix this. Perhaps we should hide the labels for those below a given percentage...

**Comment by phl0** [comment]
Just wanted to suggest that. Maybe just ignore everything below 5%?

**Comment by magicbug** [comment]
Or just show the labels on roll over of the area of the pie chart.

**Comment by AndreasK79** [comment]
@magicbug they do that now, but I like this design better. I'll see if I can find some way to not display the ones with low percentage. Worst case, I disable the label plugin.

**Comment by AndreasK79** [comment]
@phl0 could you test this one? I set it to 1% just to see how it works out now.

**Comment by phl0** [comment]
Looking fine for me:

Screenshot from 2022-09-19 09-37-42

Screenshot from 2022-09-19 09-37-49

**Comment by AndreasK79** [comment]
@phl0 thanks. I think that must be the solution then.

@magicbug could you test it out and see if it's ready for merge?

**Comment by phl0** [comment]
Looking good from my side :)

**Comment by magicbug** [comment]
Looks ok my end

**Pull request merged**
