### PR TITLE
Oqrs system

### PR DESCRIPTION
**Pull request by AndreasK79**
1. OQRS is enabled in station location.
2. Email alert is enabled in station location. Email settings need to be set in global options.
3. QSL information is set in station location.
4. If a match for a QSO is found, it is marked as requested in the database.
5. You can see a list of the open requests in admin and oqrs requests.
6. The ones that are matched, are found in print requested qsls.
7. OQRS can be set as done or deleted.
8. I've added buttons to check for all QSOs with the call.
9. You can also see all QSOs within 30 minutes of the time submitted.

### CODE REVIEW

**Comment by AndreasK79** [comment]
> I had a look and have to say its nice :) Just that I cannot find any QSO with LA8AJA... Must be something wrong with my database :)

Your DB must be corrupt :) 

Still a long way to go, but much of the user interface has been done.

**Comment by magicbug** [comment]
Reopened as it closed when I merged Dev into master

**Comment by AndreasK79** [comment]
Thought you didn't want any QSL requests :p

**Comment by magicbug** [comment]
> Thought you didn't want any QSL requests :p

After some radio events, I might not disagree with you 😃

**Comment by AndreasK79** [comment]
Any feedback here? It's been very quiet.

**Comment by cats-shadow** [comment]
Clouwdlog's own OQRS would be very useful, in my opinion.

**Pull request closed without merging**
