### PR TITLE
[Gridmap] Added gridsquare map with filtering

### PR DESCRIPTION
**Pull request by AndreasK79**
image
Can now filter gridsquare map on band/mode/sats/confirmation.

image
Added a legend with numbers.

image
And a separate menu item.

### CODE REVIEW

**Comment by phl0** [comment]
Voting for this option. We could think about dropping the old one in favor of this.

**Comment by magicbug** [comment]
Ageed seems to make sense that this is a replacement seems to do everything better

**Comment by phl0** [comment]
I guess we would need a(nother) solution for the public maps. Just keep the existing map for public and the gridmap code for logged-in users?

**Comment by AndreasK79** [comment]
So just remove the old menuitem and merge?

**Comment by magicbug** [comment]
Yep

**Pull request merged**
