### PR TITLE
Make various field inputs upper case on input

### PR DESCRIPTION
**Pull request by phl0**
This addresses issue https://github.com/magicbug/Cloudlog/issues/1485 along with some other fields that are supposed to be upper case only (e.g. DARC DOK).

### CODE REVIEW

**Comment by Werzi2001** [comment]
@phl0 I like this. Was just wondering if it would be needed/better to do it via JavaScript or server side? Doing it by CSS only affects the output and the stored values are still lower case. Might that cause problems elsewhere (e.g. ADIF export/import)?

**Comment by phl0** [comment]
> @phl0 I like this. Was just wondering if it would be needed/better to do it via JavaScript or server side? Doing it by CSS only affects the output and the stored values are still lower case. Might that cause problems elsewhere (e.g. ADIF export/import)?

Let me check. The QSO input stuff has strtoupper in the PHP code anyway. So on logging the values are converted to upper case before storing to the data base. I will check and (if missing) also add strtoupper to the code that handles editing of QSOs.

**Comment by phl0** [comment]
Just checked. The input for callsign and grid is converted to upper case even if you input lower case in the edit QSO window. So my fix should be sufficient and addresses only the display in the browser so it shows what is stored.

**Comment by phl0** [comment]
Following the discussion in https://github.com/magicbug/Cloudlog/issues/1485 I added a few more strtouppers to make e.g. DARC DOK also uppercase on server side. Also fixed @Cadair's request for the contest logging section.

**Pull request merged**
