### PR TITLE
Cabrillo export

### PR DESCRIPTION
**Pull request by AndreasK79**
Cloudlog can now export a logged contest to a Cabrillo format.

@magicbug I took your dead branch and revived it.

Now has a front-end for export.

I have not tested this format in any contest robot, so revisions are to be expected.

Thanks to @phl0 for testing and input.

### CODE REVIEW

**Comment by magicbug** [comment]
Asked on Twitter hopefully someone knows

**Comment by phl0** [comment]
Seems we need some adjustments:

Screenshot from 2023-04-14 15-26-13

**Comment by phl0** [comment]
This is fixed now. CQ WW log checker does not give errors any more :)

**Comment by AndreasK79** [comment]
I'm merging so that others can test this from dev.

**Pull request merged**
