### PR TITLE
Sort QSL images by last added to be on top

### PR DESCRIPTION
**Pull request by phl0**
I think it would be nice to have the latest images at the top of the QSL images table rather than at the bottom.
Also thought using qsoid but that is not necessarily ordering by QSO date.

### CODE REVIEW

**Comment by phl0** [comment]
Enabled that. Only issue now is that the date column (at least for d.m.Y format) sorts alphabetically instead of per date. Any workaround for this?

Screenshot from 2022-05-09 10-12-17

**Comment by AndreasK79** [comment]
I guess you need to consult datatable documentation about setting datatypes.

**Comment by AndreasK79** [comment]
@phl0 try this commit out. Got it working with all formats..

**Comment by phl0** [comment]
@AndreasK79 Works ok for me now after slight correction of the opening PHP tag ;-)

**Comment by AndreasK79** [comment]
@phl0 oops, I was a bit quick there. Sorry about that. My config allows the short tag, so I didn't notice.
If you are happy with this, I'll gladly merge it in.

**Comment by phl0** [comment]
np np.It works with the long tag now. As the xode uses the longer one throughout obviously I thought it would also make sense here. Go for merge :-)

**Comment by phl0** [comment]
np np.It works with the long tag now. As the xode uses the longer one throughout obviously I thought it would also make sense here. Go for merge :-)

**Pull request merged**
