### PR TITLE
[Search] Added tab to check for duplicate QSOs

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by AndreasK79** [comment]
I've added another tab in search:
image
When clicking callsign, you go to the search and get all QSOs listed with the callsign.

**Comment by AndreasK79** [comment]
I know. I just noticed this myself. The list is correct, but only the first call works. 

I will look into it.

**Comment by AndreasK79** [comment]
Thanks. Not sure how to do the back-link though. The way this is built, means that they are separate pages. I will think about it.
Right now, I'm thinking about this one:
image

**Comment by AndreasK79** [comment]
> on my system it does not work, it delivers the dublicate list but clicking on a callsign delivers the list of the first row callsign.
This has been fixed in dev now.

**Comment by dg9vh** [comment]
Yes, working now :-) Mni tnx!

**Pull request merged**
