### PR TITLE
[BUG FIX] Empty results if click on "More QSOs" in QSO Windows

### PR DESCRIPTION
**Pull request by HB9HIL**
This fixes a bug, if it shows empty results if click on "More QSOs" in the QSO Windows. 

The POST reference was renamed since Quicklog to avoid form fields with the same ID

### CODE REVIEW

**Comment by HB9HIL** [comment]
@magicbug Wait with that pls
Probably It needs something more

**Comment by HB9HIL** [comment]
Changed the id's back to callsign since this doesn't cause a buggy behaviour of quicklog anymore (since this is using localStorage now instead of GET).

**Review by int2001 — APPROVED** [review]
checked click/search from:
- Dashboard: Works
- LBA: Works
- Overview: Works
- Search: Works

Without that previous QSOs are not searchable by click

**Comment by HB9HIL** [comment]
@magicbug now it's good 😄

**Review by phl0 — APPROVED** [review]
Tested. Works ok.

**Pull request merged**
