### PR TITLE
[QSO] fix menu action display

### PR DESCRIPTION
**Pull request by abarrau**
after speaking with @HB9HIL , i propose this PR about dropdown menu view. 
hope it will be ok for you

for test : 
- logbook page = ok
- search = ok (but left position = improvement to think about)
- advanced search = ok (but left position = improvement to think about)
- analytics / gridsqure map = ok 
- analytics / Activated Gridsquare = ok
- analytics / Distances Worked = ok
- awards / cq / table = ok  - map = /!\ (result don't display on clic ?)
- awards / DOK / table = ok
- awards / DXCC / map = ok (but display qso detail is very slow)
- awards / FFMA = not tested 
- awards / IOTA / map = /!\ (result don't display on clic ?)
- awards / gridmaster (tested only on JA Gridmaster) = ok .. todo = tested more
- awards / WAJA / map = not tested 
- awards / WAS / map = not tested 

i can not tested all page, sorry (didn't have data)

### CODE REVIEW

**Comment by AndreasK79** [comment]
@abarrau great work. This is a nice fix.

Tested working most places:

* FFMA does not work.
* CQ Map works
* IOTA Map works
* WAS / WAS Map works
* WAJA / WAJA Map works
* Also tested the rest, except for gridmaster

For IOTA and CQ map, you need to click the label to get the popup.
Not tested the gridmaster maps. @phl0 could you do a test here?

**Comment by abarrau** [comment]
@AndreasK79, thanks for feedback 
how can i test the "FFMA" ? (some data example for testing that ?)

**Comment by AndreasK79** [comment]
> @AndreasK79, thanks for feedback how can i test the "FFMA" ? (some data example for testing that ?)

@abarrau yes. Log a QSO with USA on 6M with grid FN44.

**Comment by abarrau** [comment]
ok, i have find the fix for ffma (it was on ffma.js) ... but not access to my dev for make fixe. 
i will do this after the 3st january ... tnx

**Comment by AndreasK79** [comment]
@abarrau no problem. I pushed the FFMA fix to this PR.

**Comment by AndreasK79** [comment]
The Gridmaster maps are tested as well. It's merge time. Thanks @abarrau for the good job! Keep it up.

**Comment by HB9HIL** [comment]
@abarrau  Congrats :)

**Comment by abarrau** [comment]
Thanks all

**Pull request merged**
