### PR TITLE
Qrb calculator added

### PR DESCRIPTION
**Pull request by AndreasK79**
Pops up with ALT-Q.

### CODE REVIEW

**Comment by AndreasK79** [comment]
Locator 1 is fetched from the active station location.
image

**Comment by phl0** [comment]
I like this :) PRred some minor beauty stuff that fell into my eyes: https://github.com/AndreasK79/Cloudlog/pull/9

**Comment by AndreasK79** [comment]
@phl0 thanks. All suggestions are welcome. I'm not saying this is complete, but at least it can be tested before merge :)

**Comment by magicbug** [comment]
Guess next thing might be  to improve the gridsquare functions in Cloudlog to accept 8 characters to improve things

**Comment by AndreasK79** [comment]
@magicbug globe icon would be cool. You are thinking that it should then be triggered to show the path from the station locator to the QSOs gridsquare?

Agree that the QRA-library should be improved. As you might have seen, I'm using it here to calculate everything.

**Comment by magicbug** [comment]
> @magicbug globe icon would be cool. You are thinking that it should then be triggered to show the path from the station locator to the QSOs gridsquare?

Yes

**Comment by AndreasK79** [comment]
I'll merge this now, and see if I can figure something out regarding globe icon.

**Comment by magicbug** [comment]
Should be able to use Font Awesomes `<i class="fa-solid fa-globe"></i>` with a "link" or a html button.

**Comment by AndreasK79** [comment]
Yes, and then some modifications to spawn the dialog with everything drawn up. I'll se what I can do.

**Pull request merged**
