### PR TITLE
Add sig and sig_info to station #688

### LINKED ISSUE #688: Add 'My Sig' and 'My Sig Info' to station profile in order to support WWFF or similar
I operate regulary portable in the WWFF (https://wwff.co/) contest/award, so I would like to add a WWFF reference (e.g. DLFF-0029) to my station profile. In the ADIF Export, this should be something like:

`<MY_SIG:4>WWFF <MY_SIG_INFO:8>DLFF-0029`

I am willing to implement this for myself, but I would love to have some help in planning the needed steps and I need somebody to review my code.

### PR DESCRIPTION
**Pull request by daccle**
This adds sig and sig_info fields to the Stations model. The given information will be part of the log in the columns COL_MY_SIG and COL_MY_SIG_INFO. This information is useful for things like WWFF.

This is my first pull request, please review in depth and please give me some feedback.

Should fix #688

### CODE REVIEW

**Comment by daccle** [comment]
I will need to add this to `views/adif/data/exportall.php` in order to have in the export as well. Will fix that tomorrow

**Comment by magicbug** [comment]
Fantastic, I'll give this a test this afternoon and make sure its all OK first glance at the code seems ok

**Review by magicbug — CHANGES_REQUESTED** [review]
- When editing a station profile its populating Signature into the SOTA Field

**Comment by daccle** [comment]
Hi Peter!
I fixed the edit error and rebased on top of the current master.

**Pull request merged**
