### PR TITLE
Link to the eQSL image in log

### PR DESCRIPTION
**Pull request by myzinsky**
A link to the eQSL card image is inserted to the log. In a future commit, the image will be cached when the button is clicked and then showed from the cache instead of forwarding to the eQSL website.

### CODE REVIEW

**Comment by magicbug** [comment]
But yes agree with @dg9vh due to API requirements storing the image locally is a must to stop abuse, plus I think roughly you'd not be opening more than 3 a minute

**Comment by myzinsky** [comment]
Okay, i will change it. I’ll keep updating here

**Comment by myzinsky** [comment]
Instead of the letter symbol we could set the link also to the received arrow? What do you think?

**Comment by dg9vh** [comment]
Think, this is a good idea from ux view.

**Pull request closed without merging**
