### PR TITLE
Added bootstrapdialog in dashboard, logbook and search. I think that …

### PR DESCRIPTION
**Pull request by AndreasK79**
…should cover it.

### CODE REVIEW

**Comment by magicbug** [comment]
Looks good, only thing missing is in the QSO area where when you type callsign and it shows previous QSOs the callsigns are clickable, shows Fancybox still now minus the map

**Comment by AndreasK79** [comment]
That's one that I missed. I will fix that one.

**Comment by AndreasK79** [comment]
@magicbug Hopefully that was the last one.

**Comment by magicbug** [comment]
Found one last item /index.php/search/filter the advanced search popups!

**Comment by AndreasK79** [comment]
I see. That one is filled in via javascript. That's the reason I missed it. Will see if I can fix that one.

**Comment by AndreasK79** [comment]
@magicbug and done... ?

**Comment by AndreasK79** [comment]
@magicbug I just thought of one thing I did, that perhaps should be removed. In footer.php, in qso_save, I run a location.reload(). The reason I did this, was so that changes to a QSO would be reflected in the award table when QSO was saved, and dialog was closed. 

This line of code is in the codebase, but since this PR is about implementing Bootstrapdialog to other parts of Cloudlog, I think a commit to this branch is perhaps the best.

What are your thoughts on this Peter?

**Comment by magicbug** [comment]
Location reload seems a good thing to have to see the changes

**Pull request merged**
