### PR TITLE
Masking QSO-Time on dashboard with **:** of not logged in

### PR DESCRIPTION
**Pull request by dg9vh**
To avoid third parties to get to much infos on QSOs.

### CODE REVIEW

**Comment by dg9vh** [comment]
If you think, it would be better to make this switchable for the user, you could add some preferences within the config?

**Comment by magicbug** [comment]
Yes I like the idea of making it optional, this could be true false activated within the /application/config/cloudlog.php file if you don't know how that works check the CodeIgniter docs

**Comment by magicbug** [comment]
I've also wondered on the dashboard whether we could hide signal reports

**Comment by dg9vh** [comment]
> I've also wondered on the dashboard whether we could hide signal reports

Hi, I made the thing now configurable like the way you wanted it :-)

Hiding the reports is not so necessary I think - hiding the time would prohibit SWLs just to grab QSOs from your log to fetch QSLs cards from you (or your QSO-partner, if it is a rare DXPedition). Reports are not the target of this I think.

**Comment by magicbug** [comment]
I actually did another commit and completely removed the date for not signed in purely to keep the interface looking tidy.

**Comment by dg9vh** [comment]
Hi, no Problem. Looks better now :-)
73 de Kim

**Pull request merged**
