### PR TITLE
Added summary for DXCC award

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by magicbug** [comment]
I had to revert this merge after commit as on my live copy i get

A Database Error Occurred
Error Number: 1140

In aggregated query without GROUP BY, expression #3 of SELECT list contains nonaggregated column 'cfmdxcc.count'; this is incompatible with sql_mode=only_full_group_by

SELECT thcv.col_band, count(distinct thcv.col_dxcc) as count, coalesce (cfmdxcc.count, 0) as cfmdxcc FROM TABLE_HRD_CONTACTS_V01 thcv left outer join ( select col_band, count(distinct col_dxcc) as count from TABLE_HRD_CONTACTS_V01 thcv where station_id = 1 and col_prop_mode !='SAT' and col_band ='80m' and (col_qsl_rcvd = 'Y' or col_lotw_qsl_rcvd = 'Y')) cfmdxcc on thcv.col_band = cfmdxcc.col_band where station_id = 1 and thcv.col_prop_mode !='SAT' and thcv.col_band ='80m'

Filename: models/Dxcc.php

Line Number: 519

**Comment by AndreasK79** [comment]
@magicbug Hmm. That is strange, but I will take another look. I get no error on my local copy here, so I'm not sure what is going on.

**Comment by magicbug** [comment]
WAS has similar problems

A Database Error Occurred

Error Number: 1055

Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'cfmwas.count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT thcv.col_band, count(distinct thcv.col_state) as count, coalesce (cfmwas.count, 0) as cfmwas FROM TABLE_HRD_CONTACTS_V01 thcv left outer join ( select col_band, count(distinct col_state) as count from TABLE_HRD_CONTACTS_V01 thcv where station_id = 1 and COL_DXCC in ('291', '6', '110') and COL_STATE in ('AK','AL','AR','AZ','CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY') and (col_qsl_rcvd = 'Y' or col_lotw_qsl_rcvd = 'Y') group by col_band) cfmwas on thcv.col_band = cfmwas.col_band where station_id = 1 and COL_DXCC in ('291', '6', '110') and COL_STATE in ('AK','AL','AR','AZ','CA','CO','CT','DE','FL','GA','HI','IA','ID','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY') group by thcv.col_band order by thcv.col_band+0 desc

Filename: models/Was.php

Line Number: 163

First paragraph explains what's happening, guessing this is related to MySQL versions

**Comment by AndreasK79** [comment]
@magicbug The WAS-summary needs a rework, as it doesn't take into account SAT-stuff. The DXCC-summary should work, but I will see if I can figure out what is going on.

**Comment by AndreasK79** [comment]
@magicbug It has to do with MySQL versions and settings. https://stackoverflow.com/questions/43481869/aggregated-query-without-group-by/43482023
I guess I'll just split them into two queries and fill the array with data. That should solve the problem.

**Pull request merged**
