### PR TITLE
Quicklog Feature

### PR DESCRIPTION
**Pull request by HB9HIL**
Maybe this could a nice additional Feature 

Reference to #2473

### CODE REVIEW

**Comment by HB9HIL** [comment]
@magicbug What is you opinion in general to a "Quicklog" Feature? Is it worth it to work on that?

**Comment by HB9HIL** [comment]
I've been thinking about your feature request, and I think it's going to be pretty tough to make sure it works well on every page.

One option would be to put the Quicklog field in the header, but that's kind of like your two-in-one idea, which goes against the usual design rules.

Another idea could be to add a setting in the user options that lets you choose whether you want to see the Quicklog field instead of the search field. However, this would mess with the design a bit and make it harder to find the search function (we'd need to add another option to the dropdown).

Right now, I'm not sure what the best way is to meet your request without messing up the basic design principles.

**Comment by HB9HIL** [comment]
Note:

In the header.php I removed 

```
<?php if ($this->optionslib->get_option('global_search') != "false" || $this->session->userdata('user_type') >= 2) { ?>
```
since this is not in use anymore (Ref: [Commit e36daaa](https://github.com/magicbug/Cloudlog/commit/e36daaa6bd5d17ba893789239f6be3c8be78eb52) )

**Comment by AndreasK79** [comment]
Gave it a test. On/off option works. Search works, quicklog works. Seems to me this is good to go.

**Comment by HB9HIL** [comment]
Problem to use Enter if Quicklog is enabled

**Comment by HB9HIL** [comment]
Added a second Quicklog Option so the User can choose what shall happen when pressing "Enter" in the Quicklog Field

**Comment by HB9HIL** [comment]
Ready for Testing and awaiting Feedback 😄

**Pull request merged**
