### PR TITLE
Added indicators, if callsign/dxcc is worked on band and mode

### PR DESCRIPTION
**Pull request by dg9vh**
like the locator-input the callsign-input is colored in red or green
the country-label is enabled with a label that tells us about worked/not wkd

### CODE REVIEW

**Comment by magicbug** [comment]
I'm guessing this works for satellite too?

**Comment by dg9vh** [comment]
I think - if the locator-code did work before *g* I just copied and pasted it from there and had also the satellite-passages within it... It would be nice, if you could test it on your live-system when active :-)

**Comment by magicbug** [comment]
Seems to work, for New DXCC can we change the label colour so instead of it being grey its something else to match 

You can find css https://getbootstrap.com/docs/4.3/components/badge/

**Comment by dg9vh** [comment]
How about using Success / Danger (green/red)?

**Comment by dg9vh** [comment]
done in https://github.com/magicbug/Cloudlog/pull/374

**Pull request merged**
