### PR TITLE
KML, DX Atlas, SOTA Export  - Style synced and translation

### PR DESCRIPTION
**Pull request by HB9HIL**
Did a little refurbish of the export menu of KML, DX Atlas and SOTA.

- synced the layout of all three menu's
- added multilanguage support
- fixed the datetimepicker issue in KML Export
- added dxcc deleted hint in the dxcc selection of the sota menu

### CODE REVIEW

**Comment by HB9HIL** [comment]
@AndreasK79 Working on that 😄

**Comment by HB9HIL** [comment]
ready

**Comment by Tamh** [comment]
This comment is unrelated to the PR, but I would like to collaborate on your translation efforts.

I'm working on my fork to complete the Spanish translation plus a couple of moving random fixed texts into translation file strings.

**Comment by phl0** [comment]
> This comment is unrelated to the PR, but I would like to collaborate on your translation efforts.

Contributions are very welcome. Just make sure that you branches are based on dev branch and that you PR against dev. We are happy to assist.

**Comment by HB9HIL** [comment]
> This comment is unrelated to the PR, but I would like to collaborate on your translation efforts.
> 
> 
> 
> I'm working on my fork to complete the Spanish translation plus a couple of moving random fixed texts into translation file strings.

If you add new language snippets to spanish you should add them aswell to all other languages (in english) to make sure the language files are consistent.

**Pull request merged**
