### PR TITLE
Various updates and a fix

### PR DESCRIPTION
**Pull request by teabreakninja**
DXCC totals incorrect
Stored procedure for finding dxcc info
dxcc country on ADIF import

### CODE REVIEW

**Comment by magicbug** [comment]
Was there a reason for removing application/logs/index.html?

**Comment by teabreakninja** [comment]
Argghh. I rm'd the logs, and inadvertently deleted the index.html. I tried to 'git add' it back in but obviously didn't work. Apologies! (still getting used to git)

**Comment by magicbug** [comment]
Haven't forgotten about this just haven't had time todo a manual merge.

**Comment by teabreakninja** [comment]
No worries. Real jobs take precedence!

**Pull request closed without merging**
