### PR TITLE
Translations (work in progress)

### PR DESCRIPTION
**Pull request by HB9HIL**
I did some work on translating Cloudlog for full multilanguage support. Is it welcome or do you have other plans with the translations? Cheers and 73 de HB9HIL

### CODE REVIEW

**Comment by HB9HIL** [comment]
If this is in common sense with Magicbug I will try to complete the whole translation of Cloudlog. Easy Translations I can do with Google Translate and more difficult ones (like chinese) I will use english to avoid empty fields

**Comment by magicbug** [comment]
No this is great, ideally the whole system needs to be translated but as you can see it is quite the undertaking.

**Comment by HB9HIL** [comment]
Well then it seems I have a bit work to do 👍 It's pretty much copy paste and I like to help

**Comment by HB9HIL** [comment]
> Hi @HB9HIL , I'm also working on translating the "French" files, don't worry about that ;)

My Plan is to make sure the Language Files over all available Options are the same and try to avoid empty fields. So I will ignore french for now 👍 :-)

**Comment by HB9HIL** [comment]
> Hi @HB9HIL , I'm also working on translating the "French" files, don't worry about that ;)

We should check each other if you create new language snippets in french so the code stays the same

**Comment by HB9HIL** [comment]
@abarrau I now updated all language snippets based on english. I didn't change any french translations but there are some new one you could translate :-) But now all languages should have english output if no text in this particular language is defined. It makes it easy now to translate step by step. Important is if adding new snippets to add them to all languages at least in english to avoid empty fields.

**Comment by int2001** [comment]
That's really a huuuuuuuge improvement, @HB9HIL - chapeau!
But i have a little fear to test all that, because you not only added langs.

Could you provide a list of php-files (Views) which were changed?!

**Comment by HB9HIL** [comment]
> That's really a huuuuuuuge improvement, @HB9HIL - chapeau! But i have a little fear to test all that, because you not only added langs.
> 
> Could you provide a list of php-files (Views) which were changed?!

No Problem

This is a short overview what I've changed

_______________________________________________________________________________________

interface_assets/footer.php - just added multilang support for "Edit QSO" 

lookbookadvanced - did a lot of work to add multilang support for nearly all buttons and filters
 	for this reason also a new filter_lang.php and added support in the autoloader

search/search_result_ajax.php - added some multilang supports for mark qso's and lookup on qrz.com and hamqth

user/add.php && user/edit.php - just small adds for multilang ("Choose language" and "Leave password blank...")

view_log/partial/.. - added some multilang supports for mark qso's buttons

view_log/qso.php - added multilang support for station details and stuff like that

_______________________________________________________________________________________

Maybe I forgot something.. :-D

I've tested it with a copy of my live system and here it worked. I'll stop for the moment and please let me know if everything is okay. 

I have some issues to add multilanguage support for dialog titles like the options dialog in the advanced logbook so I didn't touch them. 

73 HB9HIL

**Comment by HB9HIL** [comment]
PS: The biggest change is that I synced all languages (_lang.php files) based on english, but left already existing translations nearly untouched. Now there shouldn't be empty fields in other languages then english or german, even if there is no translation for that. there will be english then. 

It makes it easy to translate everything step by step as I mentioned above.

**Comment by magicbug** [comment]
Quick test here looks promising too but i'd prefer some group agreement on it before I merge into dev

**Comment by AndreasK79** [comment]
Did a test here (I hope I checked all places affected), and no problems.

@HB9HIL it is very good that you synced the files. That will help out, and hopefully translators will update files.

Did you have issues with the javascript dialogs? I have added translation a few places by adding the translation to the controller as variables sent to the view, then outputting them as js variables in the view.

@magicbug as you just released, I say that we merge this, so that we can use it in dev. As always, if problems occur, we fix.

**Comment by HB9HIL** [comment]
@AndreasK79 Well I'm not a developer. I'm paramedic with a big passion for Linux, Webapps, Development and all Stuff like that. I know a little about PHP, JS and all the others and I know how they work. But I had problems to find the right variables for the javascripted dialog boxes and so I didn't touch them. I'll check future commits to understand how they work together and become better. 😉

@magicbug I've tested it several times at this state now in different languages and from my point of view I didn't see any issues. Since the translation progress will be a never ending story there is a lot of work to do and my next PR's wont be that big. I promise 😅👍

**Comment by magicbug** [comment]
Shall merge it in, look forward to the next PR 😁

**Comment by AndreasK79** [comment]
> @AndreasK79 Well I'm not a developer. I'm paramedic with a big passion for Linux, Webapps, Development and all Stuff like that. I know a little about PHP, JS and all the others and I know how they work. But I had problems to find the right variables for the javascripted dialog boxes and so I didn't touch them. I'll check future commits to understand how they work together and become better. 😉

You are doing great. Keep up the good work, and let us know if you are stuck and need help!

**Comment by magicbug** [comment]
@HB9HIL Looks like you did a fab job with the translations so far!

**Comment by HB9HIL** [comment]
> @HB9HIL Looks like you did a fab job with the translations so far!

Thanks :-) appreciate it

But there is a lot more work to do 😆

**Pull request merged**
