### PR TITLE
Make stats publicly usable with API key

### PR DESCRIPTION
**Pull request by phl0**
Tuned the statistics function so that it allows for public usage (i.e. not logged-in) with an API key that is at least read-only.

Was requested in https://github.com/magicbug/Cloudlog/discussions/1697. So I kindly ask @M0TZO for a test and feedback here.

### CODE REVIEW

**Comment by AndreasK79** [comment]
Tested working. Perhaps it's worth mentioning that url should be called like this: cloudlogurl/index.php/api/statistics/apikey

Substitue cloudlogurl with the correct url, and apikey with the readonly key generated in api.

**Comment by phl0** [comment]
True. @M0TZO reported an error last night. Details missing. So waiting for his detailed feedback here. I guess the error was within his python client but not sure.

**Comment by AndreasK79** [comment]
Right. Well, I got numbers on each point here. They were null values before I added apikey,.

**Comment by phl0** [comment]
> Right. Well, I got numbers on each point here. They were null values before I added apikey,.

Yupp. Same here.

**Comment by M0TZO** [comment]
Once updated, can confirm it's working now. Thanks.

**Pull request merged**
