### PR TITLE
Adif regex

### PR DESCRIPTION
**Pull request by AndreasK79**
Swapping out the old iterator to split adif line into array with a regex solution. 

Benefits: Splits on tag, speed.

### CODE REVIEW

**Review by int2001 — APPROVED** [review]
tested this with importing a 350 QSO ADIF on my dev. it's working.
tested with adding QSO via API - working too

**Review by phl0 — APPROVED** [review]
Tested:
- importing errorneous ADIF file ✅
- live / post QSO logging ✅
- emptied and re-imported 20k QSOs ✅

**Comment by magicbug** [comment]
ADIF changes always make me nervous but on first look this seems OK

**Comment by AndreasK79** [comment]
@magicbug I know. I have tested it a lot, but you never know. At least it's nothing to merge for this release. I think @phl0 and @int2001 will give it some testing on their multiuser setup.

**Comment by int2001** [comment]
Tested a bit and found an issue regarding lotw.

Take a stable seat:
lotw delivers for example the state field as followed in its lotw_reports:
`<STATE:2>CA, California`
Yes. True story.

With the current parser version the "2" is ignored, and "CA, California" is pasted into COL_STATE. This violates - under certain circumstances - the maxlength at our database.

So, we need to work around that.

**Comment by AndreasK79** [comment]
Thanks for testing @int2001. I have an idea for a fix. I will implement that, then we'll see.

**Comment by AndreasK79** [comment]
@int2001 ready for a new test. Now fetches value according to number of chars.

**Comment by int2001** [comment]
the issue with the oversized STATE Column when syncing from lotw is gone.

But another issue appeared when imporing eQSL-cfms:

`Exception: mb_substr(): Argument #3 ($length) must be of type ?int, string given application/libraries/Adif_parser.php 162`

**Pull request closed without merging**
