### PR TITLE
Add reporting based on SIG/SIG_INFO to the Awards section

### PR DESCRIPTION
**Pull request by daccle**
This shall be the ring to own them all...

There are a couple of funny awards based on SIG/SIG_INFO and MY_SIG/MY_SIG_INFO like:
* WWFF
* COTA
* POTA
* GMA
... and let us not forget the the legedary TOTA event born on the [30th Chaos Communication Congress](https://events.ccc.de/congress/2013/wiki/index.php/Main_Page)

Cloudlog is capable of logging SIG/SIG_INFO and using the station profile you can add MY_SIG/MY_SIG_INFO to the log as well.

IMHO one of the main advantages of Cloudlog is. that it is not cluttered, therefore I don't want to add each of the mentioned "Awards" to Award section. However there is demand for some reporting based on SIG/SIG_INFO. See the issues:  #704 #515 

I want to add a "generic" Sig Section to the Awards section to offer some reporting based on Sig/Sig_Info, like:

'''
foreach SIG in COL_SIG:
    count different SIG_INFO
'''   

Then we would get a reporting like:

WWFF: you have 10 different spots
COTA: you have 2 different spots
FOOBAR: you have 42 different spots

In an next step we could add adif_exports based on these reports, but let us start small.

Anyone is welcome to join on this pull request. I happily grant write access to my branch.

### CODE REVIEW

**Comment by daccle** [comment]
Just FYI I take it a bit slow for the moment, since I am stepping up my test environment. My PR #703 resulted in @magicbug have to doing 38e9c18 and I don't what to be cause so such stuff again.

**Comment by daccle** [comment]
👋 @AndreasK79 
I'd love to have a hint on how to add a section to the Awards nav bar. At first I thought 94ffa35 would do the trick, but no luck. Now I added some dummy model and a sig() to the Awards controller, but still no luck. I can access /index.php/awards/sig, but SIG won't show up in the nav bar.

Do you have any advice for me on where to look? Thank you very much.

**Comment by AndreasK79** [comment]
Hi Daniel. Sure, the menu is located in header.php. Look in view and interface_assetd.

**Comment by daccle** [comment]
@AndreasK79 Thank you very much, for which reason do we keep views/awards/nav_bar.php then? 
Just wondering, if I should propose to remove nav_bar.php or use nav_bar.php with this pull request. At least I see no point in keeping nav_bar.php, when basically the same code is in header.php.

**Comment by AndreasK79** [comment]
@daccle you are right. It is no longer in use. I forgot to remove it when I changed the award menu earlier this year.

**Comment by AndreasK79** [comment]
@daccle any plans to continue on this?

Seems to me a dropdown inside the view is needed to select which award to show QSO's for.
Then handling of fetching those QSOs and displaying them.
Finally an export to export those QSOs.

**Comment by AndreasK79** [comment]
Got everything working:
image
image

**Comment by magicbug** [comment]
I am going to close this now as https://github.com/magicbug/Cloudlog/commit/023766063e6e4bc899e94f51771400291f4e4511 adds this functionality however usual thing either use Discussions or Issues to get things fixed etc.

**Pull request closed without merging**
