### PR TITLE
[PHP8.1] Added some fixes for PHP 8.1

### PR DESCRIPTION
**Pull request by AndreasK79**
Credits to @mattmelling. I found these on his fork.

Everything seems to work ok on my local test.

@phl0 mind testing on 8.1?

### CODE REVIEW

**Comment by mattmelling** [comment]
Sorry, should have submitted these changes upstream to you guys. Policy on changes to CodeIgniter is clearer now so will bear that in mind.

My fork is to support NixOS which updates quite quickly and php7 support was dropped in last month's release, hence the hacky changes.

**Comment by phl0** [comment]
> @phl0 mind testing on 8.1?

Sure: https://github.com/AndreasK79/Cloudlog/pull/15

**Comment by phl0** [comment]
Apart from that the big bunch of errors on top are now fixed. Previously it looked like this:

Screenshot from 2022-12-14 13-11-46

**Comment by AndreasK79** [comment]
> Fix for the maps: [AndreasK79#16](https://github.com/AndreasK79/Cloudlog/pull/16)

That is also one way to fix it. I fetched the updated file from the CI report and pushed.

**Comment by AndreasK79** [comment]
@phl0 did you find any more places that PHP8.1 didn't work?

**Comment by phl0** [comment]
> That is also one way to fix it. I fetched the updated file from the CI repo and pushed.

Ok I guess it also fixes the maps issue? If so I will just close my PR.

**Comment by AndreasK79** [comment]
@phl0 yes, it does. I thought you were looking into other stuff, sorry.

**Comment by phl0** [comment]
No worries. Still clicking myself through stuff.

**Comment by phl0** [comment]
Finished. The rest seems to work ok. But no guarantee :D

**Comment by phl0** [comment]
Just tested your 8.1 branch on my PHP 7.4.3 installation. No issues ;-)

**Comment by AndreasK79** [comment]
Thanks @phl0.

@magicbug wanna test before merge?

**Comment by magicbug** [comment]
seems OK to go into dev branch

**Pull request merged**
