### PR TITLE
Add map for activated grids by activators

### PR DESCRIPTION
**Pull request by phl0**
This adjusts the activators listing a little and adds a link to a map showing all grids activated per activator.

Screenshot from 2022-06-12 13-52-01

### CODE REVIEW

**Comment by AndreasK79** [comment]
Just tested. Worked ok here. What about also marking the field(s)? That way, one can actually get a hint that something is marked in the map. When I now open the map, all I see is a world map with nothing marked. This of course, is that the map is zoomed. Another solution might be to center the map somewhere and zoom in when opening the map.

What do you say?

**Comment by phl0** [comment]
It is there but only for higher zoom levels. Maybe also Display while zoomed to World?

**Comment by AndreasK79** [comment]
I do not have any fields marked, only gridsquares, and those are only displayed when zoomed in. If they are supposed to be shown, I need to check the code and see if I can figure out why I don't have then.

**Comment by AndreasK79** [comment]
What I mean is something like this:
image

**Comment by phl0** [comment]
> I do not have any fields marked, only gridsquares, and those are only displayed when zoomed in. If they are supposed to be shown, I need to check the code and see if I can figure out why I don't have then.

oh sorry misunderstood. Fields are not marked. Only 4 digit grids. I think centering would be also a good option. But would require some more code to find the Center point. I might go with the fields option first...

**Comment by AndreasK79** [comment]
No problem. Great work with the PR!

Another suggestion. Add this in general.css:

#mapactivators {
	height: calc(100vh - 380px) !important;
	max-height: 900px !important;
}

**Comment by phl0** [comment]
> Another suggestion. Add this in general.css:
> 
> #mapactivators { height: calc(100vh - 380px) !important; max-height: 900px !important; }

Added. Still need some time for the marking of fields.

**Comment by phl0** [comment]
Think I got it. @AndreasK79 could you please try latest commit and report?

Screenshot from 2022-07-02 22-40-36

**Comment by AndreasK79** [comment]
@phl0 thumbs up from me. Seems to me that you nailed this one. If you are happy, I'll merge.

**Comment by phl0** [comment]
> @phl0 thumbs up from me. Seems to me that you nailed this one. If you are happy, I'll merge.

Confirmed. Didn't work on the first try on my side. But may have been a cache issue. Seems fine now. OK for merge from my side.

**Comment by AndreasK79** [comment]
@phl0 merge time :)

**Pull request merged**
