### PR TITLE
Fill US county from callbook / logbook

### PR DESCRIPTION
**Pull request by phl0**
This adresses issue https://github.com/magicbug/Cloudlog/issues/1066 and uses mechanism from DOK fill feature for populating US county with content.

### CODE REVIEW

**Review by magicbug — COMMENTED** [review]
My only comment and it probably affects a few of the functions is that will check ALL qsos in the table rather than just the ones associated with the user/logbook I mean its for a county / state so we could argue it helps provide more data but option to anyone else's thoughts on this

**Comment by phl0** [comment]
But that may give more than one result then?

**Comment by magicbug** [comment]
yup

**Comment by phl0** [comment]
Ok,  how would you decide which one to take then?

**Comment by AndreasK79** [comment]
Order by date and limit to 1 result. The last one is the most probable one.

**Comment by phl0** [comment]
> Order by date and limit to 1 result. The last one is the most probable one.

Jupp that is what I imoplemented.

**Comment by AndreasK79** [comment]
> > Order by date and limit to 1 result. The last one is the most probable one.
> 
> Jupp that is what I implemented.

Ah, I see that now :) Then I think this is fine as is.

**Comment by AndreasK79** [comment]
@phl0 tested working ok after query fix. Merge time :)

**Comment by phl0** [comment]
Oops. Must have been drunk while coding :) Tnx fix.

**Pull request merged**
