### PR TITLE
Dxcc award map

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by phl0** [comment]
Whow this is a cool feature :) I like it

**Comment by AndreasK79** [comment]
It was an idea I had for a long time. After making the WAZ map, I could do much of it in the same way.

**Comment by AndreasK79** [comment]
@magicbug any objection to merge?

**Comment by magicbug** [comment]
Sorry been out all weekend, go for merge in dev

**Comment by AndreasK79** [comment]
> Sorry been out all weekend, go for merge in dev

Hope you had fun on 10m :)

Merged, and now working on the IOTA map.

**Comment by magicbug** [comment]
777q

**Pull request merged**
