### PR TITLE
Generalize band and also use in QSO entry

### PR DESCRIPTION
**Pull request by phl0**
Addresses https://github.com/magicbug/Cloudlog/discussions/844 by using default band also for QSO entry. Also some cleanup in view.

### CODE REVIEW

**Comment by phl0** [comment]
Not sure if I should also rename variables and especially SQL table column names?!

**Comment by HB9HIL** [comment]
If you change files in application/language/.. you have to change these files in all available languages in order to stop getting the languages unsynced. If you change just english and german the other languages wont work anymore ;-)

**Comment by HB9HIL** [comment]
> If you change files in application/language/.. you have to change these files in all available languages in order to stop getting the languages unsynced. If you change just english and german the other languages wont work anymore ;-)

just put in english in the other language files

**Comment by phl0** [comment]
Good point. Done.

**Comment by AndreasK79** [comment]
> Not sure if I should also rename variables and especially SQL table column names?!

I think that should be done. Makes it less confusing for others looking at the code.

**Comment by phl0** [comment]
Updates branch and renamed both variables in code and database. Please review and comment :)

**Comment by HB9HIL** [comment]
tested and worked :-)

**Pull request merged**
