### PR TITLE
SimpleFLE bug fixing

### PR DESCRIPTION
**Pull request by HB9HIL**
Fixing some reported issues.

### CODE REVIEW

**Comment by HB9HIL** [comment]
This PR should fix following bugs:

- support for 'lsb' and 'usb'
- warning if no time is set
- if you don't set a freq the default freq is pulled by band from db

**Review by int2001 — APPROVED** [review]
working great. Errormessages are guiding me to add an time - as expected

**Comment by int2001** [comment]
Added a PR to fix a small Bug when no Grid is provided to your Repo @HB9HIL .
@magicbug plz wait b4 merging to dev here.

**Comment by HB9HIL** [comment]
> Added a PR to fix a small Bug when no Grid is provided to your Repo @HB9HIL .
> 
> @magicbug plz wait b4 merging to dev here.

thank you 😁

**Comment by HB9HIL** [comment]
Ready for Review and merge :)

**Pull request merged**
