### PR TITLE
[Custom map] Added mode and propagation selection

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by phl0** [comment]
I like the idea. But I also have an issue which you might please check?
Now if I select a from and to date and show the map the dates are lost. So if I just want to change the specific mode for the given time line I have to select from and to date again. Can we somehow make that persistent when showing the map? Just as the the other drop down boxes obviously are.

**Comment by AndreasK79** [comment]
@phl0 I know what you mean. I tried, but I haven't managed to fix that yet. I fixed it for band/mode/propagation.

I managed the same size on all though :)
image

**Comment by phl0** [comment]
@AndreasK79 Thats good. Maybe it has to do with some(JS) code that presets current date and time on loading the page?
(Just a rough guess without having looked at the code)

**Comment by AndreasK79** [comment]
@phl0 give it a go. Should work better now :)

**Comment by phl0** [comment]
Tested and working good now. Go for merge (I cannot mark it as reviewed here?)  :-)

**Comment by AndreasK79** [comment]
@magicbug wanna test, or should I merge?

**Comment by magicbug** [comment]
Let me have a quick test during tomorrow to make sure everything is up to scratch

**Comment by phl0** [comment]
The tomorrow after today :D

**Pull request merged**
