### PR TITLE
Add support for QSO Detail translations

### PR DESCRIPTION
**Pull request by leroydiazg**
To continue helping with translations, I decided to start by myself adding support for translations in the 'QSO Details' lightbox (as this is one of my father's most used view from Cloudlog).

Notes:
* I tried using already existing keywords, but also created the ones missing / incomplete.
* The "Station profile" is still hardcoded, becuase I've seen there are many parts of the project where these keywords are used (i.e. administration-> add station, or main view) and maybe it would be better to have all related keywords in one single lang file - perhapts station_lang.php? -

TO-DO:

* Station profile
* Gridsquare and Gridsquare (multi)
* USA-related fields
* File size warning

### CODE REVIEW

**Comment by magicbug** [comment]
Based on this PR I'm guessing its largely untested? on English most of the word tags are incorrect and need resolving.

Please remember when doing PRs they must be tested

**Review by magicbug — CHANGES_REQUESTED** [review]
The PR in its current state is rejected, lots of the tags are missing or don't show and its quite clear its not been tested

**Comment by leroydiazg** [comment]
I have reviewed the whole file again and, besides these two lines using ‘general_words_*’ instead of ‘general_word_*’, I have found one mistake (geneneral_word_country instead of general_word_country).

Of course this PR was tested in both English and Spanish languages. Honestly, after many hours changing lines and having not enough data by myself to make good examples of QSO, and the fact that the code hides empty fields instead of showing them in blank, made these 3 bad lines slip into the PR.

> The PR in its current state is rejected, lots of the tags are missing or don't show and its quite clear its not been tested

Honestly, this affirmation sounds a bit rude, especially bearing in mind that it is useless to do it without giving to the contributor any hint about what is wrong. If you saw mistakes during your own test, why not list them to ease the process or polishing it?

Besides these 3 tags that are already fixed, which ones do you mean? The ones in the ‘to-do’ section in the PR description?

This PR was sent in its current state because:

- I was hoping to have some feedback (perhaps any hint on how to continue doing translations?) 

- I expected to have it merged partially at the same time I got feedback (see the point above) so I (or someone else) could finish it in next iterations.

- The lack of translation guidelines. I have looked so far in discussions, issues and even pull requests to search for hints on how you would like translations. For example, as I said in my original message, Station profile lines will be used in other views (admin views) and in my opinion they all should be grouped in a single file, ‘station_lang.php’, and the same for QSO/QSL, but in this case we can find QSO and QSL translations in general_words.php, qso_lang.php and qslcard_lang.php. Another example with USA states and counties: would you leave them hard coded or make them translatable? 

If in the original PR you didn’t see any more mistakes, I think it could be merged now with the corrections so you can go ahead with #886 too and then keep working on the rest of translations.

So, feel free to add as many commits as needed to have it in good shape if you like to use my contribution.

BTW, while testing those changes, I found a bug:

- Go to ‘QSO -> Live/Post QSO’ (to create a new QSO)

- Open any QSO shown in ‘Previous Contacts’ on right side

- Click ‘Edit QSO’

- Click the ‘Notes’ tab, and see how it opens the notes tab in the background and not in the popup.

**Comment by leroydiazg** [comment]
I've been waiting for two weeks now to see any answer, hint or review to my comments and questions on this PR, and still got no answer at all.

It also looks like contributions like this one are not that much appreciated (not even spending time in reading comments), or the translations are not a main priority (though it's "the year of translations").

This situation only motivates me to stop contributing here and will focus in making the changes I need in my own fork, as I also don't have that much time to spend it waiting for answers or guidelines.

I wish you the best of luck in this project :)

**Pull request merged**
