### PR TITLE
Add distance to tweet

### PR DESCRIPTION
**Pull request by dg9vh**
if QRA-locator is set, distance is calculated and added with value to tweet

### CODE REVIEW

**Comment by phl0** [comment]
Nice. I like this idea. Will test this branch.

**Comment by phl0** [comment]
Tested successfully.

**Comment by phl0** [comment]
Tested successfully:

Screenshot_20220809-223739_Twitter

**Comment by dg9vh** [comment]
Just waiting to merge :-)

**Comment by phl0** [comment]
Screenshot from 2022-08-24 17-37-01

This might need another line of code so that this only applies to QSOs where a grid is actually logged :)

**Comment by phl0** [comment]
Maybe this helps:

https://hastebin.com/ifijodetet.pl

**Pull request merged**
