### PR TITLE
Add the possibilty to log SIG and SIG_INFO

### PR DESCRIPTION
**Pull request by daccle**
This would solve the issues for Park2Park and Castle2Castle and WWFF2WWFF contacts. Like described in #700 and #704 

This still work in progress

### CODE REVIEW

**Comment by daccle** [comment]
I am pretty sure that I got all possible spots to add SIG and SIG_INFO. There is no report in the AWARD section though, but one would have to figure out a clever solution to get all the possible stuff based on SIG/SIG_INFO. I don't want to add something for WWFF, POTA, COTA and so on. There must be a more general solution.

**Comment by daccle** [comment]
I have rebased on top of the current master and added the now missing fields to AdifHelper

**Comment by magicbug** [comment]
Looks great, we might need to add some info to https://github.com/magicbug/Cloudlog/wiki/Logging about the SIG fields and what they are used for.

**Comment by daccle** [comment]
Okay, I write some documentation in the wiki. Since I am non-native writer of English, some proof-reading is highly apreciated.

**Comment by daccle** [comment]
@magicbug I've added a very brief information about the general tab in the wiki. I guess we should invest some time and love on the wiki.

**Comment by magicbug** [comment]
Shall have a read this evening, but yes wiki always needs some love seen your Issue and will get involved and get some new images up 👍🏻

**Pull request merged**
