### PR TITLE
[Custom map] Responsive map

### PR DESCRIPTION
**Pull request by AndreasK79**
Small changes to be able to use custom map id.
This allows for setting of height in custom css.

Added CSS for height in custom map to be relative.

### CODE REVIEW

**Comment by phl0** [comment]
What could be tested here? Overwriting height value in custom.css?

**Comment by AndreasK79** [comment]
I guess that would be the only thing in this case.

**Comment by phl0** [comment]
I just set 

```
.custommap {
   height: 400px;
}
```

in my template's overrides.css to no avail. What am I doing wrong?

**Comment by AndreasK79** [comment]
It's and ID not Class. Try
```
#custommap {
   height: 400px;
}
```

**Comment by phl0** [comment]
No change. I expected the map to be smaller as per default but cannot see a difference.

**Comment by AndreasK79** [comment]
Thanks for testing. I removed !Important. Pull latest commit, it should work now.

**Comment by phl0** [comment]
Screenshot from 2022-03-17 12-48-47

Seems the overriding still does not work...

**Comment by AndreasK79** [comment]
```
#custommap {
	height: 400px !important;
}
```

Add !important like above.

**Comment by phl0** [comment]
Ok, now confirmed working! Tnx

**Comment by phl0** [comment]
Go for merge :)

**Comment by AndreasK79** [comment]
Thanks for testing. @magicbug any objections?

**Pull request merged**
