### PR TITLE
[QSL Card] Feature for adding more QSOs to a QSL Card

### PR DESCRIPTION
**Pull request by AndreasK79**
This was requested a while back. 
@magicbug please try it out.

### CODE REVIEW

**Comment by magicbug** [comment]
Looks great, can we add some more info to the View QSL area

My point being for example like this with two G0ABIs, be nice to say have the QSO Date & Time perhaps

Screenshot from 2021-07-22 17-35-34

**Comment by AndreasK79** [comment]
I've added more information to the table now. 

Not sure about the enter issue. Needs some investigation.

**Comment by AndreasK79** [comment]
Enter does not close the modal anymore.

**Comment by magicbug** [comment]
Perfect :)

**Pull request merged**
