### PR TITLE
[QRB Link] Fixed correct home locator. Now uses the one logged.

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by Werzi2001** [comment]
@AndreasK79 Interesting, didn't even know this exists. As far as I can tell from the code that should be the grid locator in the logbook/dashboard lists. Anyhow in my system these are just plain text without the link around them. Do I have to enable something to get that?

**Comment by AndreasK79** [comment]
@Werzi2001 I added this very recently into station_logbook. Spawn with ALT-Q.
Then I added the globe icon to spawn the dialog from logbook, dashboard and QSO dialog.

However, I didn't think to use the connected gridsquare from the location (an error on my part). I added so that it fetches the gridsquare from the station location connected to the QSO.

Could you elaborate on what you mean by plain text?
The globe link looks like this: 
image

**Comment by Werzi2001** [comment]
@AndreasK79 I see. I thought that this was an "older" feature and you just added the fix now to use the correct grid square. My system is not 100% up-to-date so the feature just isn't in there already.

**Comment by AndreasK79** [comment]
@Werzi2001 fix for a new feature :)
image
image

**Pull request merged**
