### PR TITLE
PR to create stable release 2.4.6

### PR DESCRIPTION
**Pull request by magicbug**
As per the title really create a new stable release of 2.4.6 as its been a few weeks.

### CODE REVIEW

**Comment by magicbug** [comment]
@phl0 @int2001 @AndreasK79 

Any Objections.

**Comment by int2001** [comment]
Still testing things here. If everything is going well i'll approve tonight or tomorrow early in the morning.

**Comment by magicbug** [comment]
Thanks, think overall it looks stable, within reason its the age old thing of sometimes just having to risk it

**Comment by phl0** [comment]
I will check and test tonight. QRX

**Comment by AndreasK79** [comment]
I think we should merge in the last German language translations, then release,

And if some bugs show up that we haven't found, we'll fix it.

**Comment by magicbug** [comment]
In that case with that vote go for merge :)

**Pull request merged**
