### PR TITLE
Load gridmap on page load

### PR DESCRIPTION
**Pull request by phl0**
Show gridmap on page load using default form settings.

### CODE REVIEW

**Comment by AndreasK79** [comment]
I would very much like this being optional. 99% of the time, I'm not interested in seeing the default map.

**Comment by int2001** [comment]
is working for me.
Tested user-config and gridview.

**Comment by phl0** [comment]
Added text for all bands. Tnx

**Comment by AndreasK79** [comment]
Tested working. And with default values set, nothing to complain about. Merge time.

**Pull request merged**
