### PR TITLE
Add Frequency to selectable colums and previous QSOs

### PR DESCRIPTION
**Pull request by phl0**
Addresses https://github.com/magicbug/Cloudlog/issues/1823 and lets the user choose Frequency as user column. Also fixes some code formatting issues.

### CODE REVIEW

**Comment by magicbug** [comment]
Do we think this is ready for merge @AndreasK79 @phl0 .. tested and seems OK.. I'm leaving last opinion to @AndreasK79

**Comment by AndreasK79** [comment]
Testes ok, so yes.

**Comment by phl0** [comment]
We just had a discussion and each posted another fix. So good to go from our side.

**Comment by magicbug** [comment]
Well done chaps :)

**Comment by phl0** [comment]
> Well done chaps :)

TU

**Comment by AndreasK79** [comment]
@phl0 did all the work on this one, so the credits goes to him.

**Comment by phl0** [comment]
No worries. Its teamwork :)

**Pull request merged**
