### PR TITLE
[Quick lookup] New feature to quickly check worked/confirmed on band/…

### PR DESCRIPTION
**Pull request by AndreasK79**
…mode. Invoked by ALT-L

### CODE REVIEW

**Comment by magicbug** [comment]
@AndreasK79 Looks really good, seems fairly fast for my setup too with 30,000+ QSOs in the database

**Comment by AndreasK79** [comment]
@magicbug once I realized I didn't need some of the looping, that helped a lot. That meant I could fetch all info for the table in just 2 queries instead of having 2 queries for each mode. Adding more to search for is also pretty straightforward now.

**Comment by AndreasK79** [comment]
Guess you can merge it so that others can get to test it as well.

**Comment by magicbug** [comment]
Agreed no news is good news in my opinion

**Pull request merged**
