### PR TITLE
Improved Countries Breakdown

### PR DESCRIPTION
**Pull request by dg9vh**
by showing confirmed (by paper-QSL) and needed confirmed.

image

### CODE REVIEW

**Comment by magicbug** [comment]
I'm concerned that this would cause confusion because is not obvious that the bracketed number is for paper and generally isn't an important stat well in my opinion at least.

**Comment by dg9vh** [comment]
So would it be better to remove the number in brackets and rename "confirmed" to "Confirmed(Paper-QSL)"?

I think the number of confirmed countries would be valuable... we could divide it also into 3 numbers (Confirmed Paper/EQSL/LoTW)

Would this be an idea?

**Comment by dg9vh** [comment]
I added mentioned thing. Now it looks like this:
image

So needed is as it was before, only the row "confirmed" has been added now...

**Comment by dg9vh** [comment]
Hi Peter, how about die PR now? Or would you commit it, if we make it configurable-visible via config-file?

**Pull request merged**
