### PR TITLE
Simple Fast Log Entry

### PR DESCRIPTION
**Pull request by HB9HIL**
It was topic in the discussions and is a great efficient way to get the paper logs from the outdoor sessions into cloudlog. 

'Fast Log Entry', or simply 'FLE' is a system to log QSOs very quickly and efficiently. Due to its syntax, only a minimum of input is required to log many QSOs with as little effort as possible.

FLE was originally written by DF3CB. He offers a program for Windows on [his website](https://df3cb.com/fle/). [Simple FLE](https://github.com/ok2cqr/sfle) was written by OK2CQR based on DF3CB's FLE and provides a web interface to log QSOs.

Now this cool tool should find its place in Cloudlog.

**It's still in progress. The current status is:** 

- Basic functionality is given
- Added Info box about FLE
- Removed 'Sample Log' - Button and added 'Syntax Help' - Button (~~Syntax Help Text is pending~~)
- Operator Call is prepopulated but editable
- Multilanguage Support is missing

Still working on that. 👍 

Any contribution is welcome 😄

### CODE REVIEW

**Comment by magicbug** [comment]
Its looking great, be fun it it would select the active location.

The sat nerd in me wonders whether we can define sat name/mode instead of WWFF/SOTA e.g. OKFF-2068 or even a different award maybe make that area tabbed @phl0 thoughts?

Is status meant to show anything or am I missing something obvious?

**Comment by magicbug** [comment]
Another random thought is perhaps we should save the input text FLE format into local storage in the browser just in case you exit the page without saving

**Comment by AndreasK79** [comment]
> Another random thought is perhaps we should save the input text FLE format into local storage in the browser just in case you exit the page without saving
> 
> Its CQWW this weekend but I'll be back and will poke myself at this next week

Local storage is implemented (I submitted that to SFLE a few years back).

**Comment by HB9HIL** [comment]
> Its looking great, be fun it it would select the active location.
> 
> The sat nerd in me wonders whether we can define sat name/mode instead of WWFF/SOTA e.g. OKFF-2068 or even a different award maybe make that area tabbed @phl0 thoughts?
> 
> Is status meant to show anything or am I missing something obvious?

Active Location: I can add the prepopulation for that

SAT: This is something we could check if the whole "construction" is working properly. It's pretty difficult actually to figure out how we get the bandslist from CL into this code. At the moment the bands are hardcoded in the javascript provided by OK2CQR (even '70CM' is hardcoded as string). We try to figure that out. 

Status: Should show an alert if no station is chosen or operater call is missing. Could use a bootstrap alert for that. 

Local Storage: It already save the FLE data in the local storage. Here at testing is does not get lost if I change pages and return. But probably it would be nice to add user_id to that data.  As Andreas already mentioned. (was to slow to send this comment 😆 )

Have fun at CQWW 😄 I would be really happy about help with that.

**Comment by HB9HIL** [comment]
> Its looking great, be fun it it would select the active location.
> 

done

**Comment by HB9HIL** [comment]
I added several UI/UX features

- removed the "Status:" at the bottom

You can try following:

- Click on Reload QSO List without data in the textarea ("Enter the data")
      -> Textarea with a red border for 2 seconds
  
- Click on "Save in Cloudlog" without data in the textarea 
      -> Textarea with a red border for 2 seconds

- Click on "Save in Cloudlog" with data in the textarea 
      -> Performing "Reload QSO"
      -> Confirmation and if click OK a "success" Message
      -> Clear Session

- Click on "Clear logging session"  
      -> Confirm the clearing
      
      
*Clearing the logging session: 
Station Call and Operator wont be cleared anymore.

**Comment by HB9HIL** [comment]
Here is your text with corrected spelling and grammar:

I added a tabbed area/design, as mentioned by @magicbug. It offers many more options for customizing SFLE for Cloudlog (Sat, dedicated SOTA/IOTA/POTA/WWFF, and so on).

It's not complete yet, but it's in its base preparation stage 😄.

Also, the localStorage is now tagged with the user ID, so multi-user installations (hundreds of users like @int2001 😉 ) have no problem with changing the account and having some other user data in the data field.

The QSO logging directly to Cloudlog works pretty well so far, thanks to @AndreasK79.

I will add multi-language support as the last part if everything else is completed.

**Comment by HB9HIL** [comment]
Removed the tabbed design because since we choose a station location the Signature Info like SOTA, POTA, IOTA and WWFF should get pulled by the station location. This is why it's unnecessary to have dedicated fields for that. Same applies to the own grid.

**Comment by HB9HIL** [comment]
Multilanguage Support is done

Last points on the ToDo:

- Improve Syntax Detection (buggy RST,...)
- Add Support for POTA and IOTA
- Test everything

After these points and some testing it's ready in my eyes :)

PS: Because some of the other PR's also edited some of the language files, this PR will maybe run in a branch conflict. But this is no problem and can be easily fixed 👍

**Comment by HB9HIL** [comment]
Ok. "day +" or "day ++++++" should work now. but the "day" command has to be in its own line. 

something like "day ++ 40m ssb" doesn't work at the moment

**Comment by HB9HIL** [comment]
We catched the basics and fixed some bigger issues. I think it's ready for testing.

**Comment by magicbug** [comment]
Post CQWW recovery going OK, will check it out this evening @HB9HIL and report back

**Comment by HB9HIL** [comment]
Thx :)

**Comment by AndreasK79** [comment]
Tested the basics. Works, but I am no expert regarding FLE by DF3CB. Seems ready to merge to get some feedback.

**Comment by magicbug** [comment]
Yep lets take it into the wild for some testing in the dev branch

**Pull request merged**
