### PR TITLE
Workable hamsat passes

### PR DESCRIPTION
**Pull request by phl0**
This adds a user account option to configure the hams.at private feed key and allow the hams.at page to show only workable passes.

### CODE REVIEW

**Comment by magicbug** [comment]
Merged a little early some errors 

A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$hamsat_key

Filename: controllers/User.php

Line Number: 501

A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$hamsat_workable_only

Filename: controllers/User.php

Line Number: 507

**Comment by phl0** [comment]
I shall have a look a fix.

**Comment by magicbug** [comment]
Got the errors fixed with the commit I just added, but its not saving the field data at the moment

**Comment by magicbug** [comment]
OKay so its saving okay, its just not getting the data from the user config table and displaying it on the form

**Comment by magicbug** [comment]
OK think i've fixed it :)

**Comment by phl0** [comment]
Ok tnx.

**Comment by phl0** [comment]
Jepp. Its fixed. I missed to copy over the port to user options table. D'oh :)

**Comment by stevendodd** [comment]
This is a great feature thank you. Is there any way to also show FM satellites - at the moment I am just seeing linear and data

**Comment by magicbug** [comment]
We dont filter by satellite type? its showing what passes people plan to activate.

**Comment by stevendodd** [comment]
Ah; shame they don't give you access to the pass data. I guess it's the whole purpose of the website to support Rovers

**Comment by magicbug** [comment]
I'm honestly confused? https://hams.at allows the user to find and select passes they plan to operate this is any mode/sat what this PR shows are those activations that are within the footprint of your grid you have given to hamsat. You can of course not provide the API key and it will show you everything that's planned around the world.

**Comment by stevendodd** [comment]
Yes I know I looked after your previous comment. I was just saying it's a shame the hams.at<http://hams.at> API doesn't allow you to show all pass data whether they are activated or not

On 21 Mar 2024, at 16:24, Peter Goodhall ***@***.******@***.***>> wrote:



I'm honestly confused? https://hams.at<https://hams.at/> allows the user to find and select passes they plan to operate this is any mode/sat what this PR shows are those activations that are within the footprint of your grid you have given to hamsat. You can of course not provide the API key and it will show you everything that's planned around the world.

**Comment by phl0** [comment]
Well this is not the (primary) purpose of hams.at. You can lookup all possible passes there though.

**Pull request merged**
