### PR TITLE
[Admin User Menu] Show Callsign in List and Option to send Passwort Reset Link

### PR DESCRIPTION
**Pull request by HB9HIL**
The first PR in 2024 🎉 Happy New Year to everybody 🎊

This introduces a slightly new admin user list. Not the same but similar to the Station Locations Table. 

Also new is the option to send a passwort reset link to an user. For the first time we use HTML E-Mails which are way more nicer than just plain text. 

email

### CODE REVIEW

**Comment by HB9HIL** [comment]
Ready to test

**Comment by HB9HIL** [comment]
I also added a "Last Login" Timestamp to the users database and in the users table. This is pretty handy to see the activity of the own users 

lastlogin

**Comment by int2001** [comment]
it is working. Great feature. Makes it easier to onBoard new Users.

But: I would strongly recommend to NOT use HTML. HTML-Mails increase the Spam-Score.

Example:
`No, score=2.6 required=3.5 tests=BAYES_40,HTML_MESSAGE,`

**Comment by HB9HIL** [comment]
As @int2001 mentioned I moved back to plain text E-Mail.

**Comment by magicbug** [comment]
Yep plain text is always best for basic emails like resets obviously sometimes HTML does make sense when you need a table but pretty doesn't always win :)

**Comment by electricEngineer** [comment]
Finally tried it out out and works like a charme!!! Thanks for your effort. Maybe the time of last PW reset would be better to know in the admin interface than last login...

**Pull request merged**
