### PR TITLE
[Print Requested QSLs] Bugfix for ADIF export. Fixed #761

### LINKED ISSUE #761: PHP Error with the "Print Requested QSLs" function
i have a problem when i try to create the ADIF for QSL Print export

i get some PHP Errors in the exported .ADI File

it looks like that the problem is in the "Filename: libraries/AdifHelper.php" file , but i am not a PHP expert ., so maybe someone can help me with this

<ADIF_VERS:5>3.1.0
<PROGRAMID:8>Cloudlog
<PROGRAMVERSION:3>Version 1.7
<EOH>

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_callsign</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 74</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_city</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 76</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_country</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 78</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_dxcc</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 80</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_gridsquare</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 82</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_gridsquare</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 86</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_iota</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 89</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_sota</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 91</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_cq</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 93</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_itu</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 95</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_cnty</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 97</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_sig</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 113</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: stdClass::$station_sig_info</p>
<p>Filename: libraries/AdifHelper.php</p>
<p>Line Number: 115</p>

</div><CALL:6>PY5ZUE<BAND:4>13cm<MODE:3>SSB<FREQ:8>2400.175<FREQ_RX:9>10489.675<QSO_DATE:8>20201220<TIME_ON:6>142148<TIME_OFF:6>142148<RST_RCVD:2>59<RST_SENT:2>59<QSL_RCVD:1>N<QSL_SENT:1>R<COUNTRY:6>BRAZIL<GRIDSQUARE:6>GG24VV<SAT_MODE:3>S/X<SAT_NAME:6>QO-100<PROP_MODE:3>SAT<NAME:12>Conrad W. O.<OPERATOR:6>DO4BMW<eor>

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by do4bmw** [comment]
if i change it , this is the result

here is a screen of my code http://prntscr.com/w6pv1s


An uncaught Exception was encountered
Type: ParseError

Message: syntax error, unexpected '$this' (T_VARIABLE)

Filename: /var/www/html/application/models/Adif_data.php

Line Number: 27

**Comment by AndreasK79** [comment]
@do4bmw a semicolon is missing in the first line that was changed.

**Comment by do4bmw** [comment]
> @do4bmw a semicolon is missing in the first line that was changed.

many thanks , ADIF is now exporting without errors !

BUT ! The QSL_SENT_VIA field is missing in the export

**Comment by AndreasK79** [comment]
@do4bmw I've added it to the ADIF export. I just checked the history, and it seems it has not been exported before.

**Comment by dg9vh** [comment]
Within the CSV it would be 👍 
So you see, how often this print-functionality is used... sadly not to often it seems...

**Comment by do4bmw** [comment]
> @do4bmw I've added it to the ADIF export. I just checked the history, and it seems it has not been exported before.

wonderfull , works now !

many thanks

**Comment by AndreasK79** [comment]
@dg9vh you are right Kim. It can't be much used, since I changed the ADIF-export about a month ago. Luckily the change I made, makes it easy to add fields to the export.

@do4bmw great to hear that it works now!

**Comment by dg9vh** [comment]
The QSL-Printing was my baby but I didn't saw by myself that I forgot the via in adif :-)

**Comment by AndreasK79** [comment]
@dg9vh I understand. Well, you can't remember everything :)

**Pull request merged**
