### PR TITLE
Import county from LotW matches

### PR DESCRIPTION
**Pull request by phl0**
Addresses https://github.com/magicbug/Cloudlog/issues/1910

### CODE REVIEW

**Comment by ofadam** [comment]
Just tested and it works like a charm!

**Comment by phl0** [comment]
Tnx fer test. Ready for merge :)

**Comment by magicbug** [comment]
Are we handling said field already existing? or just going to overwrite with lotw data 

Just checking

**Comment by phl0** [comment]
> Are we handling said field already existing? or just going to overwrite with lotw data
> 
> Just checking

We are going to overwrite with LotW data which makes sense in my eyes. I guess the LotW confirmation has the correct data in case of difference?

**Comment by magicbug** [comment]
Good with me, just double checking

**Comment by ofadam** [comment]
A little context on my request... there are times when the callbook has a county listed, but the operator is mobile (especially with Parks on the Air.) When they submit their LoTW logs, they indicate the correct county – so this makes sure that all is accurate. Thanks to both of you!

**Pull request merged**
