### PR TITLE
navbar to center, awards table header to sticky

### PR DESCRIPTION
**Pull request by teabreakninja**
Fixed the navbar to center

Made the awards table header sticky, to make viewable throughout scroll

### CODE REVIEW

**Comment by dg9vh** [comment]
After getting this into production, I recognize a problem with the z-axis and the layout of the nav-menu.

image

as You can see on the screenshot, the map-layer is overlaying the menu-structure. This also happens with other components like Table-headers and so on...

**Comment by dg9vh** [comment]
I think, it has something to do with sections in "card"-css-class.

**Comment by magicbug** [comment]
Yes, also removes the grey background going all the way along, so had to revert the pull for the top elements the table for dxcc heading however functions fine!

**Comment by dg9vh** [comment]
Yes, now it's working ok - maybe we get the nav-bar nice again later :-)

**Comment by magicbug** [comment]
Its actually simple case of the container div needed to be inside the <nav> tags just about to commit the change

**Comment by magicbug** [comment]
Resolved and commited

**Comment by dg9vh** [comment]
looks fine now :-)

**Pull request merged**
