### PR TITLE
[Dashboard] Added some warnings

### PR DESCRIPTION
**Pull request by AndreasK79**
I added some warnings to the dashboard.
1. Country file trouble is probably the biggest issue
2. PHP version is not checked anywhere, so added a check
3. We must have a logbook
4. We must have a location
image

Don't mind the PHP version. I flipped the checks to get them to display

### CODE REVIEW

**Comment by magicbug** [comment]
Looks good, if your happy merge it!

**Comment by HB9HIL** [comment]
+1 👍 Looks good :)

**Comment by phl0** [comment]
I am afraid the code does not work as expected. 
Truncated my DXCC table:

Screenshot from 2023-10-31 08-30-55

But Dashboard (with debug output says):

Screenshot from 2023-10-31 08-31-50

It obviously counts the number of rows returned. And this will always be 1 I think. So maybe this helps:

https://github.com/AndreasK79/Cloudlog/pull/19

Results in:

Screenshot from 2023-10-31 08-32-35

**Comment by AndreasK79** [comment]
Thanks to @phl0 for fixing a vital part. Merge time :)

**Pull request merged**
