### PR TITLE
[Email] Added email address option

### PR DESCRIPTION
**Pull request by AndreasK79**
Now must define email address in options.

@magicbug should we define name too? They are hardcoded right now.
Forgotten password: "Cloudlog"
OQRS: "Cloudlog OQRS"

### CODE REVIEW

**Comment by magicbug** [comment]
Hmm, hard-coded doesn't seem bad for a name, I mean both those look good and make it identifiable but could just have it so it's uniform everywhere.

**Comment by AndreasK79** [comment]
I guess since we set the subject, the sender name could be what you specify in options. I'll add another option.

**Comment by magicbug** [comment]
Yep I can live with that :-)

**Comment by AndreasK79** [comment]
@magicbug yep, think this should be it then.

**Comment by phl0** [comment]
Nice. Works as expected here. Go for merge :)

**Pull request merged**
