### PR TITLE
SV Swedish translation

### PR DESCRIPTION
**Pull request by OuiWii**

### CODE REVIEW

**Comment by magicbug** [comment]
Thanks @OuiWii are the ones in /application/languages for Swedish all OK too? suspect they might be a bit behind compared to the English one

**Comment by OuiWii** [comment]
> Thanks @OuiWii are the ones in /application/languages for Swedish all OK too? suspect they might be a bit behind compared to the English one

I will check that, currently I am just translating the /system/ files

**Comment by phl0** [comment]
Wouldn't it be better to only have a look at application/language and PR the changes to CI stuff upstream?

**Comment by oh1jw** [comment]
Hi, 

@OuiWii these files are actually from **Codeigniter**, so I think it would be better to translate them to there? 
Or what do you think @magicbug

**Comment by magicbug** [comment]
@oh1jw correct! much better suited.

**Comment by OuiWii** [comment]
Will translate over there. Thanks for all! 73 SA0WII6 aug. 2023 kl. 23:17 skrev Peter Goodhall ***@***.***>:﻿
Closed #2363.

**Comment by OuiWii** [comment]
Please ignore the text after my callsign, that stuff happens when I use email to reply..

**Pull request closed without merging**
