### PR TITLE
[CQ Award] New map added

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by phl0** [comment]
Looks very nice on my end. Just noticed that there is a zone that I haven't worked at all ... :-)

(maybe make the borders a little thinner on the lower zoom level?)

Screenshot from 2022-10-12 10-52-04

**Comment by AndreasK79** [comment]
@phl0 Then you need to get on the radio and work the last one :)

I guess borders can be adjusted according to zoom level, but that's something I need to look into.

**Comment by phl0** [comment]
> I guess borders can be adjusted according to zoom level, but that's something I need to look into.

Nothing to prevent the merge. I will also have a look. Seems it is like proportinal to zoom level.

**Comment by magicbug** [comment]
This is rather lovely!

**Comment by phl0** [comment]
@AndreasK79 I made a patch for the issue with the tile URL. Actually fixes the issue plus allows to use the globally configured tile URL as source for the map :) See https://github.com/AndreasK79/Cloudlog/pull/11

**Comment by AndreasK79** [comment]
@phl0 thanks, Yes, that was added quite recently. I had forgotten.

**Comment by AndreasK79** [comment]
Works for me.

**Comment by phl0** [comment]
> Works for me.

Ok there you go: https://github.com/AndreasK79/Cloudlog/pull/12

**Comment by AndreasK79** [comment]
Looks sharper and better now. Think it should be ready for merge. Did you have a test run yet @magicbug ?

**Comment by magicbug** [comment]
> Looks sharper and better now. Think it should be ready for merge. Did you have a test run yet @magicbug ?

Yep working good here

**Pull request merged**
