### PR TITLE
Show worked before grid status

### PR DESCRIPTION
**Pull request by Manawyrm**
As talked about in #259, cloudlog now shows the worked-before status for grids:

new grid: 

worked before:

### CODE REVIEW

**Comment by Manawyrm** [comment]
Do you have a preferred style of indentation? (spaces? how wide?)
The indentation style was a bit wild in this file to begin with...

**Comment by magicbug** [comment]
I've been using tabs 4, or rather thats what Sublime is set for, but yes some are a bit all over the place!

**Comment by magicbug** [comment]
Just been trying this and it doesn't seem to change colour for me, also doesn't seem to grab data from QRZ or i've some issue going on my end

**Comment by magicbug** [comment]
Okay logged out and back in again :)

**Pull request merged**
