### PR TITLE
[Dashboard] Added VUCC

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by phl0** [comment]
Works like a charm (of course). You have my vote for merge.

**Comment by magicbug** [comment]
Main thing on my mind is what's the cost in time of page execution and optimising the best we can.

**Comment by AndreasK79** [comment]
Not very noticeable in my installation:
https://github.com/magicbug/Cloudlog/discussions/1575#discussioncomment-3544403

Suggestions for optimizing are welcome.

**Comment by magicbug** [comment]
Looks okay to me on my install merge!

**Pull request merged**
