### PR TITLE
New feature: QSL card image upload

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Review by magicbug — CHANGES_REQUESTED** [review]
PRs for migration and QSO popup window will need resolved

Image storage for eQSL I store images in /images/eqsl_card_images not sure if we need to make some changes to make sure everything goes into assets rather than in different areas

**Comment by AndreasK79** [comment]
@magicbug Should be good to go now.

As for the directory, it's up to you. I just went by what you mentioned :)

**Comment by magicbug** [comment]
Yeah tricky isn't it! i think moving to assets makes more sense not sure why i didnt brain fart i think! will have a play with this

**Comment by magicbug** [comment]
Looks good, I'd suggest being able to upload the front and back at the same time.

Not sure if its possible on upload to return me back to the QSO popup feels a bit clunky

**Review by magicbug — APPROVED** [review]

**Comment by AndreasK79** [comment]
As I went for the carousel, I ripped out the code for uploading 2 images at once. I originally had a type in qsl_images to indicate front or back, but that didn't make sense any more. 

I did try to get it to work with ajax and js, but I couldn't get it to work. I went for the regular route for now, but I agree that it would be better to just return back to the QSO popup.

**Comment by magicbug** [comment]
Carousel is OK, but having to dig back to the same QSO to then upload the other part of the card is too clunky for my liking so need to figure out a solution to that.

**Comment by magicbug** [comment]
Not sure if we can use https://github.com/CreativeDream/jquery.filer however that includes multi upload and even cropping so perhaps worth a look

**Comment by magicbug** [comment]
Sorry linked to the out of date library meant this one https://innostudio.de/fileuploader/ same as they list it looks quite decent actually.

**Comment by AndreasK79** [comment]
I agree about uploading 2 images at once. I had it working, but I ripped it out. It shouldn't be too hard to put back in.

I'll take a look at the library, but for now, I'll just add back 2 image upload.

**Comment by AndreasK79** [comment]
@magicbug Give it a go now. 2 image upload re-added.

**Comment by AndreasK79** [comment]
The fileuploader library isn't free as far as I can tell. Only free for trying, and the files are encrypted according to the website. Is this really something we should use?

**Comment by AndreasK79** [comment]
DropzoneJS and Cropper.js are both MIT. Perhaps this might be something?
https://itnext.io/integrating-dropzone-with-javascript-image-cropper-optimise-image-upload-e22b12ac0d8a

**Comment by magicbug** [comment]
I totally missed it wasn't free! yes the two you suggest look nice

**Comment by AndreasK79** [comment]
I made some progress with JS uploading. The files are uploaded, so I need to do some updating in the dialog, or perhaps I should just load the dialog again instead?

This is not with DropzoneJS and Cropper.js. I will take a look at that later.

**Comment by AndreasK79** [comment]
@magicbug I think everything should be working now with javascript. Could you give it a go and test it out?

**Comment by magicbug** [comment]
Thats better 👍🏻 shall merge it in!

**Pull request merged**
