### PR TITLE
Fix gitignore

### PR DESCRIPTION
**Pull request by phl0**
Removes (outdated) dok.txt and adds it to .gitignore

### CODE REVIEW

**Comment by AndreasK79** [comment]
@phl0 removing dok.txt will break the autocomplete feature. Then people need to run the cron job before using this feature.

**Comment by dg9vh** [comment]
But people also need to do country list updates before using cloudlog...

**Comment by AndreasK79** [comment]
And some people aren't doing that. In my opinion, it would be better to supply a correct file, that can later be updated via cron.

**Comment by dg9vh** [comment]
Yes but consequently on all files like that. Providing a system that initially runs anyway... Also with country files etc.

**Comment by dg9vh** [comment]
Run the same way on every stage...

**Comment by AndreasK79** [comment]
Then we agree @dg9vh. Everything needed, should be supplied at start, with the possibility to update.

**Comment by phl0** [comment]
That was my basic initial question. But does it help to provide a file that outdated by default? 
This already was the issue for @dg9vh in https://github.com/magicbug/Cloudlog/issues/864 ....

**Comment by AndreasK79** [comment]
@phl0 no, but you can correct that with and updated file now. The reason it was outdated, was that SDOKS weren't present, and NM was thought to be a good idea to add as well.

**Comment by phl0** [comment]
@AndreasK79 True. But this will be outdated next month as soon as the DOK info by DARC is updated. That is that I meant. :-)

**Comment by AndreasK79** [comment]
@phl0 I see. Well then, add an updated file now, then add information in the documentation that a cron job needs to be executed for this to be updated. That's all we can do.

**Comment by phl0** [comment]
That would be an option. 
Only issue then is: It is part of the github repo and cannot be added to .gitignore. Meaning it will display as changed as soon as someone updates the files locally. Or maybe even add custom strings. 
Well, I will stand back from adding that file to .gitignore and just update the dok.txt in the repo.
Agreed @magicbug @dg9vh @AndreasK79 ? :)

**Comment by magicbug** [comment]
If I followed correctly its agreed we keep the dok.txt in the file system so this can be closed for now

**Pull request closed without merging**
