### PR TITLE
Qso time

### PR DESCRIPTION
**Pull request by phl0**
This adds a separate input field for QSO end time.

### CODE REVIEW

**Comment by HB9HIL** [comment]
> tested:
> 
> * Live QSO: Working
> * Post QSO: Working
> * Live-Contest: Working
> * Post-Contest: Working
> * checking details of qso in detail-view: Working

copy that

**Comment by AndreasK79** [comment]
I have just given it a quick spin, but one thing I would like to see, is an option to always set start_time = end_time. It needs to be a user option, as this must be set on user basis.

**Comment by magicbug** [comment]
> I have just given it a quick spin, but one thing I would like to see, is an option to always set start_time = end_time. It needs to be a user option, as this must be set on user basis.

Yep this!

**Comment by phl0** [comment]
Merge conflict here due to Swedish language being updated in the meantime. So closing here and new PR with squashed commits in https://github.com/magicbug/Cloudlog/pull/2643.

**Pull request closed without merging**
