### PR TITLE
[CQ Map] Added full screen option

### PR DESCRIPTION
**Pull request by AndreasK79**
Added full screen plugin from here: https://github.com/brunob/leaflet.fullscreen
image

### CODE REVIEW

**Review by phl0 — APPROVED** [review]
Looks good and tested successfully on my end.

**Comment by 4O4A** [comment]
I'd like to help, but I don't know where to find new file :)

**Comment by phl0** [comment]
> I'd like to help, but I don't know where to find new file :)

Which file are you looking for?

**Comment by 4O4A** [comment]
cqmap.js --> version with updated plugin.
I suck in versions :)

**Comment by phl0** [comment]
It has been merged into dev branch already.

**Comment by AndreasK79** [comment]
I've added fullscreen a few other places as well.

**Pull request merged**
