### PR TITLE
[Contest Mode] Contest name added

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by dg9vh** [comment]
Looks good in your screenshot :-)

**Comment by AndreasK79** [comment]
Thanks for the text-file @dg9vh. It made the change a lot quicker to do.

**Comment by dg9vh** [comment]
No problem... 3 Minutes with excel 😂

Andreas Kristiansen <notifications@github.com> schrieb am Sa., 19. Dez.
2020, 09:12:

**Comment by AndreasK79** [comment]
Haha. My bet would have been in a text editor with replace on text 😊

**Pull request merged**
