### PR TITLE
adds TX_PWR to qso edit dialog

### PR DESCRIPTION
**Pull request by daccle**
This adds the tx power to the edit dialog. This should fix: #695

### CODE REVIEW

**Review by magicbug — CHANGES_REQUESTED** [review]
While it adds the input box, it forgets to add the business logic to save any changes to the field, this will need to be addressed before it can be merged.

**Comment by daccle** [comment]
Will do the needed edits.

**Comment by daccle** [comment]
I hope that I have found the right place.

**Comment by magicbug** [comment]
Yep that looks good to me

**Pull request merged**
