### PR TITLE
[Contesting] Removed seconds from checkIfWorkedBefore()

### PR DESCRIPTION
**Pull request by magicbug**
Removes seconds from checkIfWorkedBefore() to try resolve error in #2139

### CODE REVIEW

**Comment by petrkr** [comment]
It probably will need more investigation, because it randomly sends some datetime, which really do not know where it got, because time already passed... And few requests was sent with seconds too.

I tried chrome and firefox, so it is not browser dependent.

I trying read javascripts where they get those time value, because in Live Contest QSO after page loads, there is visible onle HH:MM, but then some javascript start "ticks" with seconds too.

In Post Contest QSO is only HH:MM, but user is able to add seconds.

I'll try this patch in my devlog environment

**Comment by petrkr** [comment]
Well,, I littlebit investigate..

difference when it is with and without seconds depends when you did "start new contest session"..

If you did it on Live contest, it is with seconds,
If you did it on Post contest, it is without seconds because user not added them and it is pre-filled without seconds

Also if you does NOT change exchange type after "Start new session" date time is empty string

And also sometimes if do "start new contest" and not change exchange type and start type callsign,, sometimes instead of empty array it's null (because getSession return null)


well... 
if you click "start new session" it will call "deleteSession" and "setSession" at once, sometimes set is faster than delete, so result is null in getSession
sometimes is delete faster and set slower... That is that javascript async hell

```
<h4>An uncaught Exception was encountered</h4>

<p>Type: Error</p>
<p>Message: Call to a member function num_rows() on null</p>
<p>Filename: /var/www/devcloudlog/application/controllers/Contesting.php</p>
<p>Line Number: 192</p>
```

**Comment by magicbug** [comment]
I'l let @AndreasK79 chime in as he knows the contesting code better than me

**Comment by AndreasK79** [comment]
@magicbug nah, this breaks the qso loading in the table for me. The sessions stores the time in that format. Removing seconds breaks the code here.

**Comment by AndreasK79** [comment]
I see another thing that might be a problem as well. If session is never set, the code still tries to check for QSOs, so I guess there are multiple ways for failure here.

**Pull request closed without merging**
