### PR TITLE
Fix typo in COL_AWARD_SUMMITED column

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Review by phl0 — CHANGES_REQUESTED** [review]
application/config/migration.php needs updated as well. Either change or accept PR https://github.com/onovy/Cloudlog/pull/1

**Comment by onovy** [comment]
fixed

**Review by phl0 — APPROVED** [review]
Tested and working here now. Closed my PR.

**Review by int2001 — APPROVED** [review]
tested this. ready 4 merge

**Pull request merged**
