### PR TITLE
Add link to SatNOGS SAT info

### PR DESCRIPTION
**Pull request by phl0**
Add a shortcut icon with link to SatNOGS satellite data.

Screenshot from 2022-08-05 08-55-37

### CODE REVIEW

**Comment by magicbug** [comment]
I'm concerned that the /logbook display is getting busy, this might be better inside the QSO info or even make the sat name clickable

**Comment by phl0** [comment]
Roger. Will change that.

**Comment by phl0** [comment]
Like that?

**Comment by magicbug** [comment]
yup

**Pull request merged**
