### PR TITLE
[Contesting] Restoring QSO table.

### PR DESCRIPTION
**Pull request by AndreasK79**
@magicbug can you test this out and see if I missed anything?

### CODE REVIEW

**Comment by magicbug** [comment]
The Contest info restores OK, but the QSO table isn't restoring

**Comment by magicbug** [comment]
OK that was strange, QSO table didnt restore after just one QSO but when 002 went in it restored from 002 onwards OK so guessing there's a bug somwhere

**Comment by magicbug** [comment]
While we're working on this the reset buttons need some work

- Reset contest session - needs to reset the exchange fields, remove the contest id etc
- Reset QSO - really should just clear out the callsign, rst R, exchange, name and comment

**Comment by AndreasK79** [comment]
> OK that was strange, QSO table didnt restore after just one QSO but when 002 went in it restored from 002 onwards OK so guessing there's a bug somewhere
> 
> When I say restored 002 onwards I mean it didn't ever show 001 again

If I log a QSO, then press F5, the table is restored. The first QSO is logged with a contestid. If you change contestid after that, that QSO will never be restored. I'm not sure how one should go about this. We need some identifier to fetch the QSOs from the DB. The query is using the contestid, but if you have any other ideas, pitch in.

**Comment by AndreasK79** [comment]
> While we're working on this the reset buttons need some work

> * Reset QSO - really should just clear out the callsign, rst R/S, exchange, name and comment

I changed the Reset QSO button. It doesn't reset the whole form anymore. I think that should be better now.

**Comment by AndreasK79** [comment]
> * Reset contest session - needs to reset the exchange fields, remove the contest id etc

It's resetting all the localStorage now, but do you mean that it also should perform the same as Reset QSO + set Contest Name to Other in form?

**Comment by magicbug** [comment]
Yes so Reset QSO should only be for resetting QSO fields when your logging the contest QSOs.. 

Resetting the contest session should reset the exchange serial to 001, clear all the qso fields, set Contest Name to Other, exchange type to serial. aka a full clean reset of contest environment.. When I press the button at the moment nothing happens

**Comment by magicbug** [comment]
As for my first comment however of the first QSO saved disappearing from the QSO table, that still happens

If I log QSO 001 then QSO 002 and reload the Contesting Page, 002 is populated but 001 is missing

**Comment by magicbug** [comment]
> As for my first comment however of the first QSO saved disappearing from the QSO table, that still happens
> 
> If I log QSO 001 then QSO 002 and reload the Contesting Page, 002 is QSO is populated but 001 is missing in the Past QSOs table

This seems to be a not every time event, think its something I'm doing rather than a bug :p

**Comment by magicbug** [comment]
OK think I have the buttons basically working how I'd expect them

**Comment by AndreasK79** [comment]
@magicbug great. Been outside in the snow here. Seems like you have taken care of refining it :)

**Pull request merged**
