### PR TITLE
Added some more date-formats and added date-format-chooser into user-…

### PR DESCRIPTION
**Pull request by dg9vh**
…add-dialog.

### CODE REVIEW

**Comment by magicbug** [comment]
When adding fields need to make sure logic supports them on the backend, added the missing code to save date format when creating a new user.

**Comment by dg9vh** [comment]
ok, mni tnx :-) I did not checked it - I thought in origin the author of the code only missed putting it into add.php :-)

**Comment by dg9vh** [comment]
So I think, now it is ready to be merged...

**Comment by magicbug** [comment]
Yep cleaned some other parts up in the code but ready to merge now

**Pull request merged**
