### PR TITLE
Only reset timers in live QSO mode

### PR DESCRIPTION
**Pull request by phl0**
Fixes https://github.com/magicbug/Cloudlog/issues/2784.

### CODE REVIEW

**Review by HB9HIL — APPROVED** [review]
confirm the bug is fixed :)

**Review by int2001 — APPROVED** [review]
fixed and working

**Comment by HB9HIL** [comment]
> Thanks for the incredible speedy bug fix. How can i fix it in my installation? running ./update_cloudlog.sh? Or do i have to replace some source code? Cheers and 73

If you don't want to change the branch you have to wait for the next release..

**Comment by phl0** [comment]
> Thanks for the incredible speedy bug fix. How can i fix it in my installation? running ./update_cloudlog.sh? Or do i have to replace some source code? Cheers and 73

Depends on which branch you are using. If you are on dev just wait for the PR to be merged. If you are on master you have to wait for a release. And otherwise you would manually have to patch according to the PR. But this will probably break future updates then and then revert before updating.

**Pull request merged**
