### PR TITLE
[QSO entry] Blanking satellite blanks mode and propagation mode. Fixe…

### PR DESCRIPTION
**Pull request by AndreasK79**
…s #983

### CODE REVIEW

**Comment by AndreasK79** [comment]
@magicbug could you merge this?

**Comment by AndreasK79** [comment]
@magicbug merge time?

**Comment by oh1jw** [comment]
@magicbug Could you merge this, please?

**Comment by AndreasK79** [comment]
@magicbug What's the issue here? Over 2 months and no comment and no merge. It's a simple javascript that blanks two fields in the form requested by @timkirby.

**Comment by magicbug** [comment]
@AndreasK79 Dont think this will cause any issue? suggest try it in station_logbooks for a bit then it can merge in with V2 parts

**Comment by timkirby** [comment]
Thank you both, this will help avoid satellite QSO data being carried forward into non-satellite QSOs!

**Comment by AndreasK79** [comment]
@timkirby for now, this is not in the master branch (the one that gets pushed out to the instances hosted by Peter). When station_logbooks is done, it will be merged into the master branch. This is done to develop, test out and fix things in a development branch first.

**Pull request merged**
