### PR TITLE
[Accumulated DXCC] Rewrote query for accumulated dxcc. Major speedup for monthly stats

### PR DESCRIPTION
**Pull request by AndreasK79**
Only the dxcc part has been touched so far. I need to know that this works for other people as well. If it does, I'll rewrote the others as well.

On my machine, I managed to decrease the time for monthly accumulated dxcc from over 30s, down to around 1s.

Anyone willing to test and give some feedback?

### CODE REVIEW

**Comment by phl0** [comment]
I tried to call the page using the old code. But my SQL server was running hot and I didn't even have a reply by 120 seconds. Using your code is now faster than a 1 second here. Thumbs up!

**Comment by AndreasK79** [comment]
@phl0 excellent. That's what I was hoping to hear. 

I always knew this was slow, but I wasn't sure how to fix it without any special windowing functions, or write a function in php to get the result. After playing around with sql today, I managed to find a replacement that seems to work a lot quicker!

**Comment by AndreasK79** [comment]
@phl0 Updated the rest of the queries now. Mind having another go?

**Comment by phl0** [comment]
QSL. Working fine on this end. Go for merge :)

**Comment by AndreasK79** [comment]
@phl0 thanks for testing.

**Comment by phl0** [comment]
uw. Rolled out to my prod system. All working fine!

**Comment by AndreasK79** [comment]
Much smoother now. Just like it should be!

**Pull request merged**
