### PR TITLE
Fixes broken OQRS

### PR DESCRIPTION
**Pull request by AndreasK79**
It seems I managed to break OQRS at one point.

Thanks to @DeveloperNeon for letting us know about it, and for suggesting a fix. Parts of this fix comes from his PR.

In my test, this should fix the problems, but always good to have others verify.

### CODE REVIEW

**Comment by AndreasK79** [comment]
@phl0 thanks for helping me test this PR at an early stage. Please verify that this works for you now.

**Comment by DeveloperNeon** [comment]
I have gone ahead and tried it, and it doesnt seem to be submitting the request. Instead of sending me to the page that says the request has been submitted successfully, it just sends me back to the select station page, with the following url: `https://kd9nsc.com/log/index.php/oqrs?qslroute=D&message=ASD&mode=club%40odarc.org`

**Comment by AndreasK79** [comment]
@DeveloperNeon thanks for the feedback. I had enter implemented at some point, but will take a look.

**Comment by AndreasK79** [comment]
@DeveloperNeon I tried OQRS with enter, and for me it does work.
Could you specify a bit more where enter is not working?
I tried grouped search, and regular search. Both seems to work fine for me.

**Comment by DeveloperNeon** [comment]
> @DeveloperNeon I tried OQRS with enter, and for me it does work. Could you specify a bit more where enter is not working? I tried grouped search, and regular search. Both seems to work fine for me.

@AndreasK79 
When I hit enter in the email field after entering my email, I get sent to the following link with no success message: `https://kd9nsc.com/log/index.php/oqrs?qslroute=B&message=test&mode=club%40odarc.org`. Nothing shows up in the OQRS Requests page as well.

**Comment by AndreasK79** [comment]
@DeveloperNeon thanks. I guess I tabbed through the form instead of using enter. I've added so that enter works from the email input.

**Pull request merged**
