### PR TITLE
Replaced signal reports on initial dashboard with country

### PR DESCRIPTION
**Pull request by ofadam**
Per this discussion: https://github.com/magicbug/Cloudlog/discussions/855

### CODE REVIEW

**Comment by ofadam** [comment]
Forgot to also change table header – this should now work as expected.

**Comment by magicbug** [comment]
While I know a few want this I'd much prefer it was selectable as to be honest I'd prefer it stayed the way it is, but maybe as my internal dxcc lookup is good.

This would be much better as a global option setting

**Review by magicbug — CHANGES_REQUESTED** [review]
**Changes needed for merge**

For this to be merged changing signal report to dashboard will need to be general by an option

**Comment by dgdavid** [comment]
@ofadam maybe the @AndreasK79's PR https://github.com/magicbug/Cloudlog/pull/897 could be source of inspiration / guide to achieve the requirement mentioned above. 

Or, who knows, perhaps @AndreasK79 could help here if you raise your hand. Just a suggestion :)

**Comment by AndreasK79** [comment]
Since this seems stale, I'll take a stab at it.

**Comment by AndreasK79** [comment]
#1019 has been added. This can now be closed.

**Comment by AndreasK79** [comment]
@magicbug close this will you?

**Pull request closed without merging**
