### PR TITLE
Adding export fields for LOTW confirmation data

### PR DESCRIPTION
**Pull request by kj4z**
Enables export of LOTW confirmation data in ADIF files.

### CODE REVIEW

**Comment by kj4z** [comment]
Actually, may be superseded by PR 1388.  That's what I get for not checking first.

**Comment by magicbug** [comment]
Yes think it does, sorry just not had time to merge it in so far this week but thankyou

**Comment by onovy** [comment]
Yes, #1388 supersedes this.

**Comment by kj4z** [comment]
I'm going to close it then.

**Pull request closed without merging**
