### PR TITLE
use station profile grid locator to calculate distance

### PR DESCRIPTION
**Pull request by Werzi2001**
The bearing/distance in the create QSO forms currently only use the locator of the user. I think it's better to use the locator of the selected station profile as that is the location that the QSO is created for.

### CODE REVIEW

**Comment by magicbug** [comment]
Gets 👍🏻 from me, think so too! 

@AndreasK79 thoughts?

**Comment by AndreasK79** [comment]
@magicbug I totally agree, but it needs one addition.

@Werzi2001 I was just testing it out, and couldn't get it to work. Turns out the gridsquare is fetched from QRZ (in my setup), and it uses logbook.php:694:function bearing when that is the case. Could you update this one too?

**Comment by Werzi2001** [comment]
@AndreasK79 You're right, I missed that. Should be fine now. Maybe you could check as well that I got all calls of "json" (just one?). I tried to search for them but "json" is not the best search term (a lot of matches) and I might have missed one.

**Comment by AndreasK79** [comment]
@Werzi2001 works as it should now, thanks. I did have a search for json. Seems to me that it's only called from qso.js, but it is difficult to know for sure. I'll dig some more tomorrow.

**Comment by AndreasK79** [comment]
@Werzi2001 I had another look. I can't find any more references, so I'll merge this one in. Thanks.

**Comment by AndreasK79** [comment]
@magicbug it seems like I can't merge this one. It says conflict, but it doesn't say what the conflict is. Could you take a look?

**Pull request closed without merging**
