### PR TITLE
Fix for Logbook Model - now loads without a logbook defined. Fixed #1481

### LINKED ISSUE #1481: [station_logbooks] Logbook Model fails to load without a logbook defined
When opening the Logbook Tab without a logbook defined a non user friendly error occurs.

image
[Logbook_Model.php Line 1004](https://github.com/magicbug/Cloudlog/blob/6fe44f3b579200b37df3763c87bc53de1c294a0a/application/models/Logbook_model.php#L1004)

This then is receiving data from the list_logbook_relationships() function in [Logbook**s**_Model.php Line 177](https://github.com/magicbug/Cloudlog/blob/6fe44f3b579200b37df3763c87bc53de1c294a0a/application/models/Logbooks_model.php#L177)

This function returns a bool if there are no records found, and then errors when opening logbook with a non-obvious error.  I believe this function should either return records or an empty array - if it returns an empty array the front end should add a user friendly error/warning that there are No station logbooks defined.

_Originally posted by @T012m3n7oR in https://github.com/magicbug/Cloudlog/discussions/1480_

### PR DESCRIPTION
**Pull request by AndreasK79**
Before these changes, the page would not load when logbook was not defined.
@magicbug agree with these minor changes?

### CODE REVIEW

**Comment by phl0** [comment]
Just tested here and look ok for me.

**Comment by magicbug** [comment]
Looks OK, ideally however I think if logbook isn't defined it would be better to display a message to the user to go set it up

**Comment by AndreasK79** [comment]
An installation wizard would be better, but how about this?
image

**Comment by magicbug** [comment]
Can we add a link to the Station Logbook section to the message, after that 👍🏻 good to merge

**Pull request merged**
