### PR TITLE
Javascript: changed to local copies of files.

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by daccle** [comment]
Looks good to me. BTW. Is there a build tool to keep track of those external libs and to keep them updated?

**Comment by AndreasK79** [comment]
I'm not aware of any build tools for Cloudlog.

**Comment by daccle** [comment]
This should fix #686 

If the there is no tooling, how does the project keep track of newer versions of this JS stuff?

**Comment by AndreasK79** [comment]
That is a good question. I think it is done manually, but @magicbug might have a system himself?

**Comment by magicbug** [comment]
Manually by me.

**Comment by daccle** [comment]
BTW: you were missing the items in application/views/qso/edit_ajax.php:15

**Comment by AndreasK79** [comment]
@daccle You are so right. Thanks for the heads up. Will look into it when I find some time.

**Comment by daccle** [comment]
I can take care of that, if you don't mind.

**Comment by AndreasK79** [comment]
Be my guest. The files should be there, just a matter of changing to local path.
It's the same thing in edit.php. I think that file is no longer in use, but can't say for sure. I think I changed over to edit_ajax everywhere.

**Pull request merged**
