### PR TITLE
[Logbookadvanced] First version of a logbook with filtering and batch processing of QSL handling.

### PR DESCRIPTION
**Pull request by AndreasK79**
Thanks to @hugosilvaparagramanet for his QSL Manger PR. I took his code, modified and expanded the functionality. It was very interesting to see how things were solved, and I learned several new tricks.

I've renamed it to Logbook Advanced. For now, I've replaced the logbook link with this one.

Some changes from the original PR.
1. Renamed it to Logbook Advanced.
2. Datatable is added to the table for a scrollable body.
3. Added a lot more filtering (dxcc, iota, gridsquare, state, and propagation mode).
4. Built the functionality behind the buttons.

This is basically a logbook with filtering and batch processing of QSL handling.

Feedback is very welcome.

A preview:
image

I've added database save for updated info from callbook, if this info does not exist in the database.
Might need to dig some more about what info is returned from QRZ or HamQTH,

### CODE REVIEW

**Comment by phl0** [comment]
Is it intended that pressing "reset" does only reset the input form and does not update the table, i.e. return to the list of all QSOs?

**Comment by AndreasK79** [comment]
That's how it's made, but can be changed.

**Comment by phl0** [comment]
> That's how it's made, but can be changed.

Ah ok. No worries. Thought it might be a bug. But WAD is OK also :)

**Comment by AndreasK79** [comment]
@phl0 refresh and try the reset now :)

**Comment by hugosilvaparagramanet** [comment]
@AndreasK79 this looks really nice, I'm a little short on time but I'll do my best to try this changes

**Comment by AndreasK79** [comment]
@hugosilvaparagramanet hope you like it. Thanks for the code and the idea.

**Comment by AndreasK79** [comment]
@magicbug I think this is pretty close to ready, if not ready for merge. The question is, if this should have it's own menu item.

**Comment by phl0** [comment]
If I may comment on this ... ;-) I would like to keep the old view as well. What do you think about this:

Screenshot from 2022-12-21 14-28-49

**Comment by AndreasK79** [comment]
@phl0 good idea. I was thinking something like that myself.

**Comment by phl0** [comment]
> @phl0 good idea. I was thinking something like that myself.

QRX I will push that to a branch.

**Comment by phl0** [comment]
The stuff is here. If @magicbug also agrees I can PR that to @AndreasK79's branch.

**Comment by magicbug** [comment]
Agree think we need to keep both for now at least

**Comment by phl0** [comment]
> Agree think we need to keep both for now at least

So https://github.com/AndreasK79/Cloudlog/pull/17 ;-)

**Comment by AndreasK79** [comment]
So... mergetime?

**Comment by magicbug** [comment]
think so! at least to dev branch for moar testing! :)

**Comment by magicbug** [comment]
Interesting, i'm guessing older mysql issue on my live setup i'm getting An error ocurred while making the request then loading it and its calling logbookadvanced/search

**Comment by AndreasK79** [comment]
Hmm, check dev tools and see if you can pinpoint the error there.

**Comment by magicbug** [comment]
ERROR - 2022-12-21 14:10:43 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12

**Comment by magicbug** [comment]
ERROR - 2022-12-21 14:03:25 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:03:55 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:04:10 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 7 - Invalid query: 
			SELECT *
			FROM TABLE_HRD_CONTACTS_V01 qsos
			INNER JOIN station_profile ON qsos.station_id=station_profile.station_id
			WHERE station_profile.user_id =  5
			
			ORDER BY qsos.COL_TIME_ON desc
			LIMIT 
		
ERROR - 2022-12-21 14:04:10 --> Severity: error --> Exception: Call to a member function result() on bool /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/application/models/Logbookadvanced_model.php 135
ERROR - 2022-12-21 14:04:59 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:05:36 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:05:54 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:06:55 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12
ERROR - 2022-12-21 14:07:05 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /home/twom0sql/domains/logbooks.2e0sql.co.uk/public_html/2m0sql/src/QSLManager/QSO.php 12

**Comment by magicbug** [comment]
Looks like i was right MySQL server version for the right syntax to use near '' at line 7 - Invalid query:

**Comment by AndreasK79** [comment]
Not really sure that is the problem. The queries doesn't use anything special or newer functions.
It might be how the query is built together.

Try to set limit 250 on line 130 in logbookmodel_advanced.php.

**Comment by magicbug** [comment]
Ignore.. changed to PHP8 and it fixed it.

**Comment by AndreasK79** [comment]
What version were you running? I'm on 7.4.8 here.

**Comment by magicbug** [comment]
it was 7.3!

**Comment by AndreasK79** [comment]
Right. Should we make sure it works on that version and older? If so, I need to set up a test machine.

**Comment by magicbug** [comment]
Maybe but I think perhaps not, just support the last "stable" release its fine on 7.4

**Comment by oe7drt** [comment]
Hi just found this via search and wanted to let you know that the advanced logbook failed on PHP 7.2.24 on Rocky Linux.

```
ERROR - 2022-12-28 22:32:49 --> Severity: error --> Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) /opt/Cloudlog/src/QSLManager/QSO.php 12
```

I haven't tried with 7.3 as you all seem to use 7.4 and I can confirm it works now. Wasn't sure because the README only shows PHP 7.

**Comment by DL3EL** [comment]
I am currently running PHP 7.4.33, all I get is "An error ocurred while making the request"... any tip?

**Comment by AndreasK79** [comment]
@DL3EL I'm not sure what the lowest 7.4 is. I'm running 7.4.8 on my dev-setup, and it works fine here, so if you can upgrade the version a little bit and try again, that should fix it.

**Comment by DL3EL** [comment]
@AndreasK79 hmm.. I would think, that 7.4.33 is newer than 7.4.8

**Comment by AndreasK79** [comment]
Oops. It should. Can you look in dev tools and see if you see any errors?

**Comment by DL3EL** [comment]
First I called Logbook Overview (1st and 2nd msg)
Then Logbook Advanced (3rd)
after that I filled the "De" Field and pressed "Search" (4th)

1st: DevTools failed to load source map: Could not load content for http://192.168.241.99/assets/css/bootstrap-dialog.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

2nd: DevTools failed to load source map: Could not load content for http://192.168.241.99/assets/js/bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

3rd: jquery-3.3.1.min.js:2          POST http://192.168.241.99/index.php/logbookadvanced/search 500 (Internal Server Error)
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
(anonymous) @ logbookadvanced.js?1672500601:142
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2
trigger @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
trigger @ jquery-3.3.1.min.js:2
w.fn.<computed> @ jquery-3.3.1.min.js:2
(anonymous) @ logbookadvanced.js?1672500601:359
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2

4th: jquery-3.3.1.min.js:2          POST http://192.168.241.99/index.php/logbookadvanced/search 500 (Internal Server Error)
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
(anonymous) @ logbookadvanced.js?1672500601:142
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by AndreasK79** [comment]
Can you click on the logbookadvanced/search link and see if the error 500 has any more info?

**Comment by DL3EL** [comment]
is there an easy way to copy the whole stuff? Export to a .har file?

image

**Comment by AndreasK79** [comment]
You need to click on the search call:
image
Then click on response on the right side. You will probably find an error there. That's the one I need to hopefully be able to pinpoint the problem.

**Comment by DL3EL** [comment]
image

image

hope that helps

**Comment by AndreasK79** [comment]
I need what is under the response link.

**Comment by DL3EL** [comment]
I thought, that was not so important :-)

image

**Comment by phl0** [comment]
Maybe set the environment to "development" in index.php temporarily to gain more info in the error.

**Comment by DL3EL** [comment]
Finally, with the help of @phl0 we could solve the issue. The root cause was, the upgrade to php 7.4 was only done on the OS level. Apache itsself was still running with php 7.3. Here is, what we did, the server is a Raspberry PI with Buster:

For better debug we enabled developer mode (index.php) and increase error level (application/config/config.php)
Install php 7.4 for OS

Make sure libapache2-mod-php7.4 is installed for Apache 2 module (root cause)
Check Admin/Debug Information, it should read "PHP Version	7.4.33"
 
If not, install it: "sudo apt install php7.4-json php7.4-curl php7.4-mbstring php7.4-mysql php7.4-zip php7.4-xml libapache2-mod-php7.4"
remove old php version: “sudo a2dismod php7.x”
(use “sudo a2dismod” to see exact name)
Enable new version: "sudo a2enmod php7.4”
Restart Apache “sudo systemctl restart apache2”

now the advance Logbook works like charme

**Comment by AndreasK79** [comment]
That is great news! Glad it's now working. Good we have a Linux expert with @phl0 here.

**Pull request merged**
