### PR TITLE
differents updates

### PR DESCRIPTION
**Pull request by abarrau**
for loading custom class from the third_party folder

### CODE REVIEW

**Comment by abarrau** [comment]
different update : 
- load custom class from third_party folder
- load custom.css file from assets folder
- use english default language if ask language file not found

**Comment by AndreasK79** [comment]
@magicbug this seems ok to merge. Can you take a look?

**Comment by abarrau** [comment]
Hi, i create other change. 
This pullrequest can be validate, before i propose other change ? 
Thanks.

**Review by magicbug — COMMENTED** [review]
Could you please explain a bit about how this works and the purpose please.

Spoke with @AndreasK79  and both feel some detail on what it does is needed

**Comment by abarrau** [comment]
Hi Peter, 

Its very long time :) 
For this 3 changes, my idea is : 

1/ load custom class from third_party folder
- i dont remember why ... i will read my dev for remember me ... (sorry) 

2/ load custom.css file from assets folder
- if people would like change a css, it can't do it on a general.css; because on update version, change will be lost. 
- with a custom.css file, change is not lost.

3/ use english default language if ask language file not found
- if you use an other language, and when you load a controler page who is not translate (on language folder), the controler page dont work ... 
- with this pullrequest, default language is "english" > the page can be load event if original langue not exist

My english is not sorry, i hope you it's ok for you.

PS: i have an other projet for you cloudlog, i developed a plugin module ... 

Aurelien / F4ANS

**Comment by AndreasK79** [comment]
@abarrau thanks for the explanation. I'll take a look and test it out.

@magicbug I don't see any harm in applying this PR. What do you think?

**Comment by AndreasK79** [comment]
@magicbug just tested this out. Everything works, no errors, and I see these things as useful. I'm merging this into master now.

**Comment by AndreasK79** [comment]
@magicbug I also like the idea that it falls back to English if the language file is missing (if language not updated or some other reason). Custom css is also not a bad idea. That way it is not overwritten with an update.

**Comment by abarrau** [comment]
Hello, 
@AndreasK79, Thanks for accept this pull request... 
I have other idea for cloudlog, but, i dont know if you will accepte ... 
See you later !

**Comment by AndreasK79** [comment]
Hi @abarrau. I liked the idea with custom css and also language fallback. Ideas are welcome. If you are unsure about them, just open a discussion and let us now. Then you can get some feedback from the community.

**Pull request merged**
