### PR TITLE
Add links to qrz.com and hamqth.com

### PR DESCRIPTION
**Pull request by phl0**
This narrows the callsign input field a little and leaves some space to display links to qrz.com and hamqth.com profiles of the corresponding callsign. 

Screenshot from 2021-12-20 08-02-21

### CODE REVIEW

**Comment by magicbug** [comment]
I quite like the idea of this Flo although probably not for everyone, happy to run it in the Station logbooks branch trying not to merge things into master at the moment while we break things for v2!

@AndreasK79 views?

**Comment by AndreasK79** [comment]
@magicbug I like this idea too. Generally I agree with you regarding pushing more stuff to master, but if @phl0 would be so kind to also make a PR based on station_logbooks, I wouldn't mind merging this both places.

**Comment by magicbug** [comment]
If you merge into master, i'll cherry pick it across would be easier I think

**Comment by magicbug** [comment]
@AndreasK79 Thats if you confirm its working OK not tested yet!

**Comment by AndreasK79** [comment]
@magicbug tested working ok. I'll merge it.

**Comment by phl0** [comment]
No problem at all. I will rebase against that branch. I shall also make this optional with a nice config option or so.
And make it switchable between icons and text as requested here:
https://twitter.com/m0tzo/status/1473278146602536964?s=20

**Comment by AndreasK79** [comment]
@phl0 thanks.

**Comment by phl0** [comment]
Well that was faster than expected. Shall I still re-base to the station locations branch here?

**Comment by magicbug** [comment]
Yep please

**Pull request merged**
