### PR TITLE
Automatic push of Docker Image to the Hub

### PR DESCRIPTION
**Pull request by iu2frl**
I created a Dockerfile to automatically build and push images to Docker Hub at every new Release that is published.

# Docker Hub preparation
## Docker Hub account
1. Create a free Docker Hub account [here](https://hub.docker.com/)
2. Once the account is confirmed, go to "Account Settings" and then "Security"
3. Generate a new "Access Token" and copy the provided key

## Create Image repository
1. In the top bar select "Repositories"
2. Create a new "Repository" following the steps

# GitHub Preparation
## GitHub Settings
1. Go in the repo Settings, select "Secrets and Variables"
3. Select "Actions"
4. Create a new Repository Secret called "DOCKERHUB_IMAGENAME" and set paste the image name, should look like "username/imagename"
5. Create a new Repository Secret called "DOCKERHUB_TOKEN" and paste the Docker Hub token
6. Create a new Repository Secret called "DOCKERHUB_USERNAME" and enter your Docker Hub username

# Publishing new image
Image is automatically published every time a new release is created, no need to manually operate.

# Final-user required steps
Once the image is published to Docker Hub, final users will only need to pull it from the Hub and execute it on their machine, no coding skills needed.

This procedure is equivalent to what is explained [here in the help](https://github.com/magicbug/Cloudlog/wiki/Installation-on-a-Docker-Container), only difference is that the image is already done and final user will only need to pull it an run it. I will create a dedicated Wiki page if needed.

The wiki page i just pasted will be updated accordingly to point to the newly created images

Sample result: [https://hub.docker.com/r/iu2frl/cloudlog](https://hub.docker.com/r/iu2frl/cloudlog)

### CODE REVIEW

**Comment by AndreasK79** [comment]
@iu2frl looks better now. Thanks.

**Comment by AndreasK79** [comment]
@iu2frl would be great if you also update the wiki with this info :)

**Comment by magicbug** [comment]
@iu2frl I've followed your steps so shall see if it works https://hub.docker.com/repository/docker/2m0sql/cloudlog/

**Comment by iu2frl** [comment]
Sure I will update the wiki ASAP.

You need to create a new release to trigger the action or go in the "Actions" tab and trigger it manually, i will then pull the image and test it

**Comment by magicbug** [comment]
OK not ready to tag anything but its ready to go :-)

**Comment by iu2frl** [comment]
I am updating the Wiki, i only need to create the "Use a prebuilt image" as soon as the next release is ready

**Comment by asemlucben** [comment]
Hi @magicbug i saw the release and i see the GitHub Action running, it should take approx 40-45 min then the image should be published!

**Comment by magicbug** [comment]
Did wonder how long it might take :-)

**Comment by iu2frl** [comment]
Image is up, I will test it asap and update the guide

**Comment by magicbug** [comment]
https://hub.docker.com/r/2m0sql/cloudlog/tags

Seems to have worked :-)

**Comment by iu2frl** [comment]
Tested! New page: https://github.com/magicbug/Cloudlog/wiki/Use-a-prebuilt-image-from-Docker-Hub

**Pull request merged**
