### PR TITLE
WAS javascript dialog qso

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by magicbug** [comment]
Thanks this is on my things to merge list today!

**Comment by magicbug** [comment]
@AndreasK79 Looks great, love the popups way nicer and the way you changed the marking QSLs.

**Comment by magicbug** [comment]
Approved, guess next jobs putting the new popup for edit on the logbook areas.

**Comment by AndreasK79** [comment]
@magicbug Glad you liked it. Yes, it has to be implemented several places. I know DXCC And CQ awars needs to have the same rework. The logbook area is also a place. After that, I'm not sure, but when all is done, the double up of files can be removed.

**Pull request merged**
