### PR TITLE
New feature: timeplotter

### PR DESCRIPTION
**Pull request by AndreasK79**
Used for log analyze. Plot time when a certain dxcc or cqzone has been worked on a chosen band.

### CODE REVIEW

**Comment by magicbug** [comment]
If you can add some wiki docs to just explain a bit what these extra analytics tools do that would be fab, happy to add images just leave me a little note

**Comment by AndreasK79** [comment]
Yeah, I'll write a few words when I get some time.

**Comment by M0TZO** [comment]
Could CSV be added? I'd like to able to export to make a pretty spreadsheet for when to operate.

**Comment by AndreasK79** [comment]
I'll look into it. The plotting tool has export functions available, I just need to figure out how to add it.

**Comment by AndreasK79** [comment]
@M0TZO by adding a few javascript files, export is available from the graph:
image

I'll submit this when I find some time.

**Comment by M0TZO** [comment]
Perfect 👍

**Comment by AndreasK79** [comment]
@M0TZO I submitted the code yesterday, just waiting for Peter to merge it.

**Pull request merged**
