### PR TITLE
End to end testing

### PR DESCRIPTION
**Pull request by patrickrb**
This pull request was branched from the #3038 branch, but could be merged independently if we close the other one.

## You can see the tests running against **this** PR here: https://github.com/magicbug/Cloudlog/actions/runs/8591149336/job/23539563254

This pull request introduces significant changes to the project, primarily focusing on the introduction of Docker and Cypress for containerization and end-to-end testing respectively. The changes facilitate the setup of a local development environment using Docker and Docker Compose, and the implementation of Cypress for automated testing. Additionally, there are updates to the `.env.sample` file and a new GitHub workflow for Cypress tests.

Docker and Docker Compose setup:

* [`.env.sample`](diffhunk://#diff-088d9f35d23a4347d221d71dd49b02b95001dff4abe637a40fe0bc04d502049cR1-R9): Added new environment variables for MySQL configuration, base locator, website URL, and directory.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1-R28): Introduced a Dockerfile for PHP and Apache with necessary system dependencies.
* [`Dockerfile-db`](diffhunk://#diff-d1762420d9fc14c60682925651b441603a2bb69eade90ac374895d101ac4c0b4R1-R8): Created a Dockerfile for MariaDB.
* [`docker-compose.yml`](diffhunk://#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R1-R25): Added a Docker Compose file to manage the services for the web application and database.
* [`script.sh`](diffhunk://#diff-116b4e2bac3e35befdfae3f3b6eb88911689c30bfe6696d9e6b0139da8cb5e72R1-R83): Added a shell script to replace placeholders in the configuration files with environment variables and start Apache in the foreground.  This eliminates the need for the install page which was necessary for automated testing.

Cypress and GitHub Workflow:

* [`.github/workflows/cypress-tests.yml`](diffhunk://#diff-115b5fe6c5afd0974d2c69d87b1b318b1fd3fd730e22d9d7fccb221bc4b374e6R1-R20): Introduced a new GitHub workflow for running Cypress tests.
* [`cypress.config.js`](diffhunk://#diff-5bae461d15457335f3d6285d35d3df2fd618e583eb7460c52cd8f0de69627abcR1-R11): Added a Cypress configuration file.
* `cypress/e2e/1-login.cy.js`, `cypress/e2e/2-version-info.cy.js`: Implemented Cypress tests for login and version info modal. [[1]](diffhunk://#diff-90b710c753d09ab0a146cce478cde295a730c2e52aca3b6249394f2e01b00641R1-R22) [[2]](diffhunk://#diff-eb80a7e92e5a96360c4da81e326ee6b7c97ea5c92457999f4856e24dfc63f237R1-R62)
* `cypress/support/commands.js`, `cypress/support/e2e.js`: Added Cypress support files for custom commands and e2e tests. [[1]](diffhunk://#diff-1b1a73ba561eab6738c8b62510feed5b10edcd25c56626ac79017752b806439dR1-R8) [[2]](diffhunk://#diff-1a2b52d55ed1bf51fa9d61ccc1c27d91bc7d0af28b49ec0905966edf07e57c18R1-R20)
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R1-R15): Added Cypress as a devDependency.

Other changes:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L14-R65): Updated the README to include instructions for setting up a Docker development environment.
* [`application/controllers/User_options.php`](diffhunk://#diff-fd827f8933d64783179d96bb994b419c5b877e46538358d564566d7945ff1e3eR62-R65): Added a new function to enable the version dialog.
* [`install/index.php`](diffhunk://#diff-e3e61d33e0b42b68fbb3ab35c6f3d22e683f04cf4e273979785127acab333d85L151-R154): Updated the installation form to pre-fill database configuration fields with environment variables.

### Login tests
gif of cypress tests running login tests locally

### Version info tests
gif of cypress tests running version info tests locally

### Login tests:
login tests github output

### Version info tests
version info github tests output

### Summary:
summary of github tests running

### CODE REVIEW

**Comment by magicbug** [comment]
Bit early for me to comment as I've just not had time to try it, that being said some testing is very much needed. 

Hopefully have some time during this week

**Comment by magicbug** [comment]
Hi @patrickrb 

Sorry for delay but finally got time to look into it all

When I do composer up I'm getting the following error 

```
cloudlog-web-1  | /usr/local/bin/docker-php-entrypoint: 9: exec: ./script.sh: not found
cloudlog-web-1 exited with code 127
```

**Comment by magicbug** [comment]
Got past that error using https://stackoverflow.com/questions/44460825/entrypoint-file-not-found

However getting 

```
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known

Filename: mysqli/mysqli_driver.php

Line Number: 203
```

**Comment by magicbug** [comment]
Ok got passed that with adding mynet see commit.

What I have noticed is that when creating the config.php

```
$config['base_url']	= 'http://localhost
';
```

It seems to add a new line which of course is a breaking item

**Comment by patrickrb** [comment]
> Cypress works fantastic and overall very happy with this PR.. @patrickrb not sure what you think about the base_url or if just ignore it could be just windows CRLF issues

Awesome, glad you were able to get it working!  Excited to see this implemented further.  

Going to be at a conference this weekend, should have some time to look at it on Sunday, thanks for trying it out and adding some fixes!

**Comment by magicbug** [comment]
> Going to be at a conference this weekend, should have some time to look at it on Sunday, thanks for trying it out and adding some fixes!

Have fun at the conference!

**Comment by magicbug** [comment]
@patrickrb did you have any ideas on the new line issue in config.php or think like me it was windows related and nothing to worry about

**Comment by patrickrb** [comment]
> @patrickrb did you have any ideas on the new line issue in config.php or think like me it was windows related and nothing to worry about

Going to take a look at it today!

**Comment by patrickrb** [comment]
> > @patrickrb did you have any ideas on the new line issue in config.php or think like me it was windows related and nothing to worry about
> 
> Going to take a look at it today!

havent been able to replicate it so far, still looking

**Comment by magicbug** [comment]
I think it was a windows one off issue, shall merge it in and see how it acts :)

**Comment by patrickrb** [comment]
> I think it was a windows one off issue, shall merge it in and see how it acts :)

Awesome, i'll start writing some more tests for some of the main stuff like submitting QSO's.  Ideally we'll write tests around areas where bugs are reported, no sense in having tests for code that doesnt break.

**Pull request merged**
