### PR TITLE
Iota map

### PR DESCRIPTION
**Pull request by AndreasK79**

### CODE REVIEW

**Comment by phl0** [comment]
Yeah. Another nice map to view :) Tnx your work @AndreasK79

**Comment by magicbug** [comment]
You'll never hear me complaining about lovely maps :D

**Comment by AndreasK79** [comment]
@phl0 enjoy. I think that concludes the award maps.

**Comment by AndreasK79** [comment]
@magicbug having a map for the award, makes things a lot more interesting :)

**Pull request merged**
