### PR TITLE
Add shortcut for copying API keys

### PR DESCRIPTION
**Pull request by phl0**
This adds a little icon which can be used to copy api keys instead of selecting the text and copying manually. Demo:

https://www.youtube.com/watch?v=9SpDfPOkIqw

### CODE REVIEW

**Comment by AndreasK79** [comment]
This only works if your page is served via HTTPS. I just could not get it to work locally, and found that it is because I don't have HTTPS on my dev machine. 

Some info here: https://stackoverflow.com/questions/71873824/copy-text-to-clipboard-cannot-read-properties-of-undefined-reading-writetext

**Comment by phl0** [comment]
whoooops. My dev env is also HTTPS. So didn't notice. Have to check if a non-HTTPS solution exists....

**Comment by AndreasK79** [comment]
A hack is described in the link above.

**Comment by phl0** [comment]
Currently working on https://github.com/magicbug/Cloudlog/pull/1582 to get that into V2. Will look here afterwards.

**Comment by phl0** [comment]
tbh the page looks like crap if served via HTTP anyway:

Screenshot from 2022-10-01 14-14-16

So not sure if we should try to fix this at all? @magicbug?

**Comment by phl0** [comment]
Screenshot from 2022-10-01 14-17-45

Screenshot from 2022-10-01 14-17-53

**Comment by phl0** [comment]
Statistics don't even work at all ....

Screenshot from 2022-10-01 14-17-53

**Pull request merged**
